vmware/vic-product

README.md

No space between these two tags [vSphere Integrated Containers Engine](https://github.com/vmware/vic)

Fixed a spacing issue

---

docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md

Removed erroneous quotation marks from the `configs` file settings for deployment of the client plug-ins for vCenter Server on Windows.
@jooskim can you please confirm that you use quotes for VCSA but not for Windows?

Removed quotes from configs file for Windows UI deployment.

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin.md
docs/user_doc/vic_vsphere_admin/upgrade_registry.md
docs/user_doc/vic_vsphere_admin/upgrading_vic.md

Fixes https://github.com/vmware/vic-product/issues/50.
@frapposelli can you please take a look? Note that I couldn't actually get this to work, the last couple of steps are taken on faith from the spec. My attempt would fail at the stage of powering the VM back on after attaching the two disks from the old install:

Added procedure to upgrade Registry

---

docs/user_doc/vic_app_dev/container_limitations.md

While going through the list of known issues from 0.9 for the 1.1 release notes, I saw that https://github.com/vmware/vic/issues/1279 is now closed and non-root users are supported. 
@emlin can you please confirm?

It looks like non-root users are now supported.

---

docs/user_doc/vic_app_dev/configure_docker_client.md

Fixes https://github.com/vmware/vic-product/issues/148.
I left the previous version with both FQDN and IP addresses in the topic, but commented it out, for reinsertion once https://github.com/vmware/vic/issues/4721 is fixed. I'll open a new doc issue to reinsert the text in the future. 
@emlin and @frapposelli is this OK? Thanks!

Removed FQDN and specified that registry IP must be used for docker login

---

docs/user_doc/vic_vsphere_admin/download_vic.md

Updated link for the automatic builds, which are now on google storage.

Replaced link to bintray with google storage

---

docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/ts_ui_not_appearing.md

Fixes https://github.com/vmware/vic-product/issues/180. 
I have completely rewritten the procedures for installing the client plug-ins based on @jooskim 's reworking of the process and on feedback from @dbarkelew  and @vmwarelab. 
Note that while I have tested these procedures to the point at which registration of the extensions succeeds and the extensions appear in the MOB for the VC (both Windows VC and VCSA), I am still unable to see the plug-ins in either client. The files are simply not uploading to either my VCSA or my Windows-based VC. 
But, pending me getting my hands on the final build for 1.1.1, can I please ask the 3 of you to review the steps as I have documented them so far? @mhagen-vmware can you also please run through the steps to see if you can get them to work? 
Thanks …

Updated plug-in installation topics

---

docs/user_doc/vic_vsphere_admin/common_vic_options.md
docs/user_doc/vic_vsphere_admin/inspect_vch.md
docs/user_doc/vic_vsphere_admin/list_vch.md
docs/user_doc/vic_vsphere_admin/open_ports_on_hosts.md
docs/user_doc/vic_vsphere_admin/remove_vch.md
docs/user_doc/vic_vsphere_admin/ts_thumbprint_error.md
docs/user_doc/vic_vsphere_admin/upgrade_vch.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md
docs/user_doc/vic_vsphere_admin/vch_shell_access.md
docs/user_doc/vic_vsphere_admin/vch_ssh_access.md

Per title, following comment from @alextopuzov that this was not mentioned consistently.

Added instruction to use colon-delimitation in thumbprint everywhere.

---

docs/user_doc/SUMMARY.md
docs/user_doc/pdf.md

In relation to https://github.com/vmware/vic/issues/5459, changed "Printable PDFs" to "Download PDF", to be more tree-friendly.

Changed "printable" to "download" for PDF links.

---

.drone.ova.yml
installer/Makefile

Disabled drone builds for the ci temporarily. 
Fixed gopath order in Makefile.

Disable ci for ova builds

---

docs/user_doc/vic_vsphere_admin/vch_installer_examples.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Per customer comment via Slack, I reinserted "Resources" into the paths when specifying resource pools in clusters in `--compute-resource`. 
@emlin is this correct? Thanks!

Added "Resources" to paths for rps in clusters.

---

docs/user_doc/book.json

Fixes https://github.com/vmware/vic-product/issues/305.
If you click the EDIT THIS PAGE link in any page in the HTML 1.1 docs, you are taken to the corresponding Markdown file in the `1.1-docs` branch of `vic-product`, rather than to `master`. This will prevent anyone from making 1.1-specific update in the 1.2 docs-in-progress.

Updated "edit this file" link to point to 1.1 branch.

---

installer/packer/packer-vic.json

Fixes #363 
Properly orders shell & file provisioners in packer.json.

Fix invalid provisioner order

---

installer/fileserver/server.go
installer/fileserver/tasks.go
installer/lib/login.go
installer/lib/ovfenv.go
installer/ovatools/vic-ova-ui/main.go
installer/packer/scripts/package_provisioning.sh
installer/packer/scripts/provision_admiral.sh
installer/packer/scripts/systemd/harbor/harbor_startup.path
installer/pkg/ip/ip.go

This change runs the PSC `register` command during the OVA init step to generate the PSC-related files in `/etc/vmware/psc`. Issue vmware/vic#5551
Tested on top of https://github.com/vmware/vic-product/pull/410 - Admiral and Harbor start correctly after the token config file has been generated.

Run PSC register command during OVA init

---

docs/user_doc/vic_vsphere_admin/introduction.md

This change corrects three minor issues in the "Overview of vSphere
Integrated Containers for vSphere Administrators" page:
- Remove a superfluous space between "images" a period. (Line 35)
- Add a missing space between a period and "If". (Line 88)
- Add a missing comma following an introductory clause. (Line 156)

Fix typographical issues in vSphere Admin docs

---

installer/fileserver/tasks.go
installer/packer/scripts/package_provisioning.sh
installer/packer/scripts/systemd/harbor/harbor_startup.path

This change runs the PSC binary's register command for admiral,
harbor and engine to create separate config and keystore files
for each component.
Issue: vmware/vic#5551

Register all VIC components with PSC during init

---

installer/packer/scripts/kov/configure_kov.sh
installer/packer/scripts/provision_fileserver.sh

fixes: https://github.com/vmware/kov/issues/337
because new certificate and key may be generated, so we have to persist vic-adm_*.tar.gz in this case to enable the restart of kov.
manual deployment verified

persist vic-adm_*.tar.gz to enable 'systemctl restart kov'

---

installer/packer/scripts/admiral/configure_admiral.sh
installer/packer/scripts/admiral/start_admiral.sh

This change modifies the docker run command for the Admiral
container to add parameters for PSC. All config/cert files
needed by Admiral are now present in one dir, which is
mounted as a volume in the container.

OVA: start Admiral container with PSC parameters

---

installer/engine_installer/engine_installer.go

Add the harbor registry as an insecure registry to the default VCH so that customers that want to play around with the default VCH can actually use the already installed and running harbor instance.

[skip ci]Add harbor registry to the default VCH

---

installer/packer/scripts/admiral/configure_admiral.sh

Previously Admiral startup failed upon restart when using user provided TLS certificates because there was an existing keystore containing a certificate with the same alias as we were trying to insert. This change deletes the existing keystore so we can add the certificate.
Fixes #447

Fix Admiral startup certs

---

installer/packer/scripts/psc/get_token.sh
installer/packer/scripts/systemd/harbor/harbor_startup.path

This change copies Harbor's `tokens.properties` file to
`/data/harbor/psc`. This is needed to support Harbor's standalone
use-case where the user may not have access to `/etc` while
attempting to mount the token file's path as a volume in the
Harbor container.
To avoid a systemd dependency cycle with the `harbor_startup.path`
unit, this change creates a marker path after the token file has
been copied and uses that path to activate `harbor_startup.service`.

PSC: copy Harbor token to volume mount

---

docs/user_doc/vic_vsphere_admin/contents_of_vic_binaries.md
docs/user_doc/vic_vsphere_admin/deploy_demo_vch.md
docs/user_doc/vic_vsphere_admin/deploy_vch.md
docs/user_doc/vic_vsphere_admin/deploy_vch_esxi.md
docs/user_doc/vic_vsphere_admin/deploy_vch_registry.md
docs/user_doc/vic_vsphere_admin/deploy_vch_vcenter.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/open_ports_on_hosts.md
docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md

Fixes https://github.com/vmware/vic-product/issues/286.
Updated all instructions relating to `vic-machine`, plug-ins, and downloads to direct users to the Getting Started page rather than downloading directly from the file server.
@andrewtchin and @jooskim can you please review? 
We will address links to the Registry interface running on port 443 in a separate PR, that will cover updates related to the unified Registry/Management portal UI.

Updated all download instructions to mention the Getting Started page.

---

installer/packer/scripts/admiral/start_admiral.sh

This change adds two JAVA_OPTS values to the Admiral container,
per request from @lazarin.

Add params to Admiral's docker run command

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Per latest OVA build from 8th August, the checkboxes to choose not to deploy Registry and Management Portal have been removed from the OVA installer. This PR updates the doc accordingly.
@andrewtchin please can you review? Thanks!

Removed options to not deploy registry/mp from OVA installer.

---

installer/packer/scripts/harbor/configure_harbor.sh

Before:
```console
$ docker login 10.160.222.67
Username: administrator@vsphere.local
Password:
Login Succeeded
$ govc vm.power -force -off vic-1.2-test
Powering off VirtualMachine:vm-117... OK
$ govc vm.power -force -on vic-1.2-test
Powering on VirtualMachine:vm-117... OK
$ docker login 10.160.222.67
Username (administrator@vsphere.local): administrator@vsphere.local
Password:
Error response from daemon: login attempt to https://10.160.222.67/v2/ failed with status: 401 Unauthorized
```
After: 
```console
$ docker login 10.160.222.67
Username: administrator@vsphere.local
Password:
Login Succeeded
$ govc vm.power -force -off vic-1.2-test
Powering off VirtualMachine:vm-117... OK
$ govc vm.power -force -on vic-1.2-test
Powering on VirtualMachine:vm-117... OK
$ docker login 10.160.222.67 …
```

Add common/config cleanup before running harbor prepare

---

installer/engine_installer/engine_installer.go
installer/engine_installer/html/exec.html
installer/engine_installer/logstream.go
installer/engine_installer/server.go
installer/fileserver/html/index.html
installer/fileserver/server.go
installer/packer/scripts/fileserver/configure_fileserver.sh

Fixes #542.
- Refactors the Engine Installer Logstreamer to wait for a response when adding the demo vch to the an admiral cluster.
- Correctly masks the password when the demo vch page is refreshed after a command was run.
- Adds auth token to admiral api requests from the engine installer.
- Adds the vic-tar.gz file from the fileserver to the Getting Started Page.
- Redirects port 80 to the tls fileserver address

Update Admiral Cluster API Request

---

docs/user_doc/vic_app_dev/container_operations.md

Looks like we only mention `docker commit` in the table of supported Docker commands. Mentioned that you can only run it on stopped containers.
Fixes https://github.com/vmware/vic-product/issues/316.
@sflxn, can you please review? Are there any other caveats that we need to mention? Thanks!

Documenting support for docker commit

---

installer/ovatools/vic-ova-ui/main.go
installer/packer/scripts/upgrade/upgrade_1.1_to_1.2.sh

Fixes #584 
Logs to `/var/log/vmware/upgrade.log`
Cleans up stdout of script to look like the following:
```
root@localhost [ /etc/vmware/upgrade ]# ./upgrade_1.1_to_1.2.sh --dbuser root --dbpass password --target 10.192.47.230 --username 'administrator@vsphere.local' --password 'Admin!23'
Starting upgrade 2017-08-17 23:23:17 +0000 UTC
Preparing upgrade environment
Disabling and stopping Admiral and Harbor path startup
Finished preparing upgrade environment
Performing pre-upgrade checks
Starting Admiral upgrade
[=] Shutting down Harbor and Admiral
[=] Upgrade Admiral
Admiral migration complete
Archiving previous Admiral data
Cleaning up
Admiral upgrade complete
Starting Admiral
Performing pre-upgrade checks
Starting Harbor upgrade
[=] Shutting down Harbor
[=] Migrating Harbor data
[=] …
```

Improve update script

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Noticed in vic-42ddaaa6.ova that the options to add SSL certs for VIC registry have been removed from the OVA. 
No associated issue. @anchal-agrawal are you a good candidate to review this in @andrewtchin 's absence? Thanks!

Removed OVA option to provide custom certs for registry.

---

installer/fileserver/html/index.html
installer/fileserver/server.go

This change adds a InitSuccessFeedback variable for the Getting
Started page's html template so we can show a success message if
the OVA init tasks (tag and PSC register) finish with success.
This commit does not include the html template changes.
Towards #554

Add success message to Getting Started page

---

installer/fileserver/html/index.html

This change adds a success alert for the Getting Started page
if the OVA init tasks finish with success.
This includes the html template changes only.
Towards #554

Add an initialization success alert

---

installer/Makefile
installer/packer/vic-unified.ovf

Building an ova file now sets the version number by replacing
"--version--" with the version set by the BUILD_VICENGINE_REVISION
environment variable.
Fixes: #252

OVA build sets version programmatically

---

installer/engine_installer/html/auth.html

This commit fixes the naming in the html template for the demo VCH
installer wizard page.
Towards #551

Make naming for demo VCH installer consistent

---

installer/fileserver/register.go

We create a timestamp file after a successful init via the Getting
Started page so subsequent visits to that page don't show the login
modal. This change creates the file in the register API code too.
Fixes https://github.com/vmware/vic-product/issues/628

Create timestamp file after init in register API

---

installer/pkg/version/version.go

The OVA console version now diplays <tag>-<commit-hash>
on the top line.
Fixes: #626

Removes the build number from OVA console version

---

installer/packer/scripts/admiral/configure_admiral.sh

Fixes #620 
Example `server.crt`
```
Aug 24 19:23:48 localhost.localdomain bash[562]: -----BEGIN CERTIFICATE-----
Aug 24 19:23:48 localhost.localdomain bash[562]: MIIFqTCCA5GgAwIBAgIJAJCYfiuuIsvwMA0GCSqGSIb3DQEBCwUAMIGTMQswCQYD
Aug 24 19:23:48 localhost.localdomain bash[562]: VQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJUGFsbyBBbHRv
Aug 24 19:23:48 localhost.localdomain bash[562]: MRUwEwYDVQQKDAxWTXdhcmUsIEluYy4xHjAcBgNVBAsMFUNvbnRhaW5lcnMgb24g
Aug 24 19:23:48 localhost.localdomain bash[562]: dlNwaGVyZTEkMCIGA1UEAwwbU2VsZi1zaWduZWQgYnkgVk13YXJlLCBJbmMuMB4X
Aug 24 19:23:48 localhost.localdomain bash[562]: DTE3MDgyNDE5MjM0OFoXDTE4MDgyNDE5MjM0OFowfzELMAkGA1UEBhMCVVMxEzAR
Aug 24 19:23:48 localhost.localdomain bash[562]: BgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEPMA0GA1UECgwG …
```

Chain self signed Admiral server cert with root

---

installer/fileserver/html/index.html

This commit removes the condition to show the re-initialize button only
when an error alert is present.
Cherry picks fccc0856a1d1de95ecb7f955ffc8c766e60e4e0c
From PR #641

Fix re-initialize button in Getting Started page

---

docs/user_doc/vic_overview/introduction.md
docs/user_doc/vic_quickstart.md
docs/user_doc/vic_vsphere_admin/deploy_demo_vch.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/installing_vic.md
docs/user_doc/vic_vsphere_admin/security_reference.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Found a load of links that include `.html` in the Markdown, that should be `.md`. 
@anchal-agrawal can you please review?

Fixed a bunch of links that used html instead of md as suffix.

---

installer/packer/vic-unified.ovf

Partial fix for this issue: https://github.com/vmware/vic-product/issues/651 .
The rest of the fixes is in the Admiral registration command (description of Example Users).

Fix typos in OVF descriptor, issue: #651

---

installer/fileserver/tasks.go

This change prevents the PSC `register` command for a component
from running if its PSC config file (`psc-config.properties`) is
present on disk at the usual location. This is to prevent multiple
PSC registrations without stopping and then starting Admiral.
This fixes the issue where the Admiral UI shows a blank page if
PSC registration has been performed multiple times using the re-
initialize appliance button or the `/register` API.
Fixes #586

Skip PSC registration if config file is present

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Fixes https://github.com/vmware/vic-product/issues/347.
In https://github.com/vmware/vic-product/issues/347 you include a procedure to convert RSA key to PKCS8. Do we need to include that in our docs, since it's generic open SSL stuff?

Added that Mgmt Portal requires PKCS8 cert key.

---

installer/packer/scripts/upgrade/upgrade_1.1_to_1.2.sh

If the --dpbass parameter is not set, pull the password from
the harbor cfg file.  If it is passed to the upgrade script,
use the passed password.
Fixes: #629

Pull dbpass from cfg in upgrade script

---

installer/fileserver/html/index.html
installer/fileserver/server.go
installer/fileserver/tasks.go

This change allows the user to specify an external PSC instance
(not hosted on the vCenter host) as an optional input field in the
Getting Started page's login modal.
Towards #771

Add support for external PSC in Getting Started page

---

installer/fileserver/register.go
installer/packer/scripts/upgrade/upgrade_1.1_to_1.2.sh

This commit modifies the OVA upgrade script to collect the optional
PSC input fields and pass them to the request to the /register
endpoint of the Getting Started page.
Fixes #837

Add support for external PSC in OVA upgrade

---

docs/user_doc/.bookignore

The `.bookignore` file prevents the `covers` and `graphic_sources` folders being included in the HTML output. The fact that the MD source files are copied into the output folders appears to be a bug in Gitbook, because the files are not in the same folder as the master `SUMMARY.md` file.

Adding .bookignore file to exclude covers and graphic_sources from builds

---

docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/894.
@hickeng I was unable to test this because the GA build is not yet available for download and this option was not present in RC3.

Added --container-name-convention option

---

installer/build/scripts/system_settings.sh

Fixes #742 , #892 
1. A warning message is print before and after login to OVA via SSH
2. SSH forwarding is disabled 
```
AllowAgentForwarding no
AllowTcpForwarding no
```
3. IPv6 ICMP redirection is disabled
```
net.ipv6.conf.all.accept_redirect = 0
net.ipv6.conf.default.accept_redirect = 0
```
4. IPv6 Router Advertisement is disabled
```
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0
```

Print warning banner upon SSH login to OVA and address scan results 

---

installer/build/build.sh

The build script uses `head -n1` in a chain of pipes to trim input. This would be fine, except that it also sets `-o pipefail` (which prevents errors in a pipeline from being masked) and `-e` (which causes the script to exit on the first error).
The result is that the script terminates when the output being trimmed by `head` exceeds one line. When this happens no output is printed, but the return value is 141 (=128+13) which tells us SIGPIPE is the culprit.
We confirm `head -n1` is the source of issue by inspecting PIPESTATUS:
```
$ gsutil ls -l "gs://harbor-builds" | grep -v TOTAL | sort -k2 -r | head -n1 | xargs | cut -d ' ' -f 3 | sed 's/gs:\/\//https:\/\/storage.googleapis.com\//'
https://storage.googleapis.com/harbor-builds/harbor-offline-installer-v1.2.0-84-g9847223.tgz
$ echo …
```

Hande SIGPIPE errors in the build script

---

installer/BUILD.md
installer/build/build.sh

1.  Correct path to build script in documentation 
2.  Display usage (instead of failing with an error) if build script called without args

Fix minor documentation issues related to the build script

---

installer/build/scripts/harbor/start_harbor.sh

Reverts the dch image tag in start harbor from `127.0.0.1:5000/default-project/vmware/dch-photon` to `127.0.0.1:5000/default-project/dch-photon`.

Fix bad dch tag in start_harbor.sh

---

installer/RELEASE.md

This change updates the RELEASE doc to accurately reflect the vic-product tagging strategy.

Update release doc with proper tagging instructions

---

docs/user_doc/vic_vsphere_admin/backup_vch.md
docs/user_doc/vic_vsphere_admin/backup_volumes.md

Fixes the formatting problem that was visible in https://github.com/stuclem/vic-product/blob/backupfix/docs/user_doc/vic_vsphere_admin/backup_volumes.md. HTML output is fine.

Formatting fix in backup doc

---

installer/build/scripts/admiral/configure_admiral.sh

Fixes #972 
```
root@localhost [ /storage/data ]# ls -al
total 44
drwxr-xr-x 7 root  root   4096 Nov  1 20:34 .
drwxr-xr-x 5 root  root   4096 Nov  1 20:49 ..
drwxr-x--- 6 10000 10000  4096 Nov  1 20:52 admiral
drwxr-x--- 2 root  root   4096 Nov  1 20:34 certs
drwxr-x--- 2 root  root   4096 Nov  1 20:34 fileserver
drwxr-x--- 7 root  root   4096 Nov  1 20:53 harbor
drwx------ 2 root  root  16384 Nov  1 20:30 lost+found
-rw-r----- 1 root  root    244 Nov  1 20:52 version
root@localhost [ /storage/data ]# cd admiral/
root@localhost [ /storage/data/admiral ]# ls -al
total 32
drwxr-x--- 6 10000 10000 4096 Nov  1 20:52 .
drwxr-xr-x 7 root  root  4096 Nov  1 20:34 ..
drwxr-xr-x 5 10000 10000 4096 Nov  1 20:51 8282
drwx------ 2 10000 10000 4096 Nov  1 20:52 ca_download
drwx------ 2 10000 10000 …
```

Set user for Admiral data directory

---

docs/user_doc/vic_app_dev/build_push_images.md
docs/user_doc/vic_app_dev/container_operations.md

Towards https://github.com/vmware/vic-product/issues/507.
As an interim fix, I have included links to @pdaigle 's blog about how to do Swarm with DCH Photon. In 1.3, I will integrate this content into the docs properly.
@pdaigle and @pescerosso is this a satisfactory short-term solution?

Added links to Patrick's DCH Photon Swarm doc.

---

installer/build/scripts/admiral/configure_admiral.sh
installer/build/scripts/fileserver/configure_fileserver.sh
installer/build/scripts/harbor/configure_harbor.sh
installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh
installer/build/vic-unified.ovf
installer/engine_installer/engine_installer.go
installer/engine_installer/html/auth.html
installer/engine_installer/server.go
installer/fileserver/register.go
installer/fileserver/server.go
installer/fileserver/tasks.go
installer/lib/login.go

Fixes #816, fixes #1014 by removing the default ovf hostname. Uses the hostname, if set, during psc registration as the admiral url.
@sergiosagu and @lcastellano can you please review for proper use of fqdn's to configure admiral and harbor?

Use Hostname in PSC registration

---

installer/build/cache.sh

This is a quick typo fix in the cache script. This bug becomes apparent when you specify a local copy of vic-engine during the OVA build.

Fix typo in cache script

---

installer/build/baseimage/install.sh
installer/build/ova-manifest.json
installer/build/scripts/systemd/vic_machine_server/vic-machine-server-logrotate
installer/build/scripts/systemd/vic_machine_server/vic_machine_server.service

Fixes #944 by:
- adding a logrotate config to the appliance
- adding a volume mount to the vic-machine-server service

Store vic machine server logs in log disk

---

docs/user_doc/vic_vsphere_admin/containervm_config.md

Fixes https://github.com/vmware/vic-product/issues/102.
@AngieCris can you please review this? I did a global search of the docs and this was the only place in which `--container-store` was mentioned.

Removed --container-store option from docs

---

installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh
installer/build/scripts/systemd/vic_machine_server/vic_machine_server.service

Fixes #973. Setting the container user in the ova systemd units instead of the dockerfile for separation of concerns.

Use unprivileged user for vic-machine-server

---

installer/build/baseimage/root/etc/systemd/system/docker.service.d/50-override-start.conf
installer/build/ova-manifest.json
installer/build/scripts/admiral/configure_admiral.sh
installer/build/scripts/harbor/configure_harbor.sh
installer/build/scripts/system_settings.sh
installer/build/scripts/systemd/harbor/harbor.service

Fixes #891 by disabling component services `harbor/admiral.service` and relying on their startup scripts `harbor/admiral_startup.service` to start. This ensures that all certs/keys have been generated or copied before harbor ui serves the cert to the client.
This also includes a docker service fix, which was preventing docker from starting on hard resets.
A quicker fix than #1103 which is more of a systemd overhaul.

Disable component services start on boot

---

installer/BUILD.md

This fixes the BUILD readme with correct file naming instructions. The naming convention used in the previous doc does not work with the OVA's UI plugin configuration.

Update installer BUILD doc with correct information

---

installer/build/build.sh

Fixes #1152.
Outputs `BUILD_OVA_REVISION=v1.4.0-dev-0-2c6792a8` on `upstream/master` branches.
Outputs `BUILD_OVA_REVISION=v1.3.0-rc2-0-9e2a95b6` on `upstream/releases/1.3.0`

Fix incorrect version string

---

installer/build/build.sh

Uses most recent tag on the HEAD branch instead of most recent 
tag on the repo. Fixes #1152.

Fix incorrect version string (#1159)

---

installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh

The `/storage/data/certs` directory does not exist on v1.2.x data disks. This change adds a mkdir for that directory in the configuration step of vic-machine-server.

Add mkdir for vic-machine-server certs directory

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_windows.md
docs/user_doc/vic_vsphere_admin/upgrading_vic.md

Per comment from @jooskim in https://github.com/vmware/vic-product/pull/1142#pullrequestreview-79576737, I am reinstating the step to restart the Flex plug-ins after upgrade.
@jooskim is this OK now? Thanks!

Reinstated the step to restart flex plugins after upgrade.

---

installer/build/scripts/upgrade/upgrade-admiral.sh
installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Fixes #1095 
I'm switching to only checking if the entire upgrade process was completed, not individual components since recovery from a single component upgrade failing was dubious at best. This cleans up files left by previous upgrades and adds a versioned timestamp file when the 1.3.0 upgrade succeeds. I think future upgrade should use `/storage/data/version` to determine if upgrade should proceed.
Testing completed with chained upgrade 1.1.1 -> 1.2.1 -> 1.3-dev

Upgrade script handles chained upgrades 

---

docs/user_doc/vic_vsphere_admin/plugins_vcsa.md

Previously the docs show http, which results in an error if the docs are actually followed to the letter. The file is served over https and since the port is not 443, https needs to be specified or the resulting tarball is corrupted.

Update VIC curl download command to https

---

tests/manual-test-cases/Group2-OVA-Features/2-06-Trusted-Content.md

This commit is the corresponding manual test update for the change
to the content trust feature, where instead of allowing access to
Harbor and Docker Hub when content trust is enabled, we now allow
access only to signed images that are on the Harbor instance.
See issue vmware/vic#6778 and PR vmware/vic#6919

Update manual test for content trust feature

---

installer/fileserver/html/index.html
installer/fileserver/server.go

Fixes #1203 
When registering appliance to VCSA, after supplying username and password to VCSA, if the login attempt fails, any validation error now shows up as a warning banner with detailed message describing why the login failed.
For example, when the VCSA cannot be reached:
when the username and password are invalid:
Before this change, the error message was generic (`incorrect username and password`) for all validation errors. However it doesn't require the html form titled "Complete VIC appliance installation" to reload (the error message banner just appears on top of the form).
Now with the change, the html form has to reload for the error banner to show up on the top. So when the error banner appears, all fields form has been cleared.

Correctly show validation error when verifying login to VCSA on OVA UI

---

installer/build/scripts/admiral/configure_admiral.sh

… when it breaks evenly on 64-character boundary, it injects a newline which borks the cert file.  patch strips blnk lines.

Fix cert formatting

---

tutorials/api/README.md

An API for VCH Management is under development and will be included in 1.3.0. While the current functionality targets a very specific use-case: enabling the implementation of a VCH creation wizard in the H5 client plugin, the API will be publicly exposed and accessible.
This tutorial attempts to explain that this pre-1.0 API is not ready for general consumption, but that it is available for experimentation and feedback is welcome. The earlier we can get feedback from future
users of the API, the better able we will be to accommodate it.

Add tutorial for VCH Management API

---

docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md

Noticed in the GA build that the VIC engine bundle includes `v` in the filename.

Fixed filename for VIC engine bundle

---

docs/user_doc/vic_vsphere_admin/upgrade_vch.md

Fixes https://github.com/vmware/vic-product/issues/1270
@jzt does this cover it? Thanks!

Mentioned that vApp VCHs remain vApps after upgrade

---

docs/user_doc/vic_app_dev/deploy_multiple_docker_compose.md

Fixes #949 
@corrieb can you please have a look whether i've removed just enough from the  "Building and Deploying Multi-Container Applications to a Virtual Container Host" topic. I couldn't find any mentions of the workaround in the https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/deploy_single_containervm.md topic, so nothing changed there.

Lost+found workaround removed from doc

---

installer/build/baseimage/install.sh

Adds the net-tools package to the vic-product
appliance to properly load gateway addresses,
fixing the mismatch with static ips. (Fixes #1267).

Fix missing gateway addresses (#1314)

---

installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Related #1333 
Slightly modified adds log message for config migration and does not add `ldap_verify_cert` key to config

Update upgrade script version detection (modified)

---

installer/build/baseimage/install.sh
installer/build/baseimage/stage.sh

Adds five seconds to the vic-product ova grub timeout. 
Fixes #1345 and contributes to #1341.

Increase grub timeout. (#1357)

---

tests/common-ova/OVA-Cleanup.robot

Fix for cleanup to run even when the copy support bundle fails. Currently, its leaving behind some OVA appliances due to copy logs failure which is impacting other builds.

Update test cleanup step

---

installer/build/Dockerfile
installer/scripts/ci-build.sh

Makes progress towards #1287 by pulling in release component versions on release branches of vic-product.
note: Not to be merge until after 1.3.1 final.

Use component release versions in release builds

---

installer/build/scripts/systemd/units/vic-appliance-environment.service

vic-appliance-environment could previously fail if eth0 wasn't present when trying to get IP

Appliance environment waits for eth0

---

docs/user_doc/vic_vsphere_admin/bridge_network.md
docs/user_doc/vic_vsphere_admin/vch_networking.md
docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md

Fixes https://github.com/vmware/vic-product/issues/1459, to replace some remaining instances of "distributed virtual switch" with "vSphere Distributed Switch".

Fixed nomenclature for VDS

---

docs/user_doc/vic_vsphere_admin/configure_vch.md

Fixes https://github.com/vmware/vic-product/issues/1445.
The doc will be reverted by https://github.com/vmware/vic-product/issues/1461 in 1.4, once https://github.com/vmware/vic/issues/7378 is fixed.
@gigawhitlocks can you please review?

Removing doc for non-functioning vic-machine configure --tls-cname

---

tests/resources/page-objects/Project-Repositories-Page-Util.robot

Text changed from ‘Project Repositories’ to ‘Project repositories’

Update project repositories page title

---

docs/user_doc/vic_vsphere_admin/ops_user_manual.md

Doc update resulting from Bugzilla issue 2064396. Added clarification to the entry about datastore folders. We already state in the table that the datacenter role should not propagate.
@hickeng @dbarkelew @lcastellano does this cover it? Thanks!

Added note about network folders to ops user config doc

---

installer/build/ova-manifest.json
installer/build/scripts/fileserver/configure_fileserver.sh
installer/build/scripts/fileserver/fileserver.service
installer/build/scripts/provisioners/provision_fileserver.sh
installer/fileserver/files/error_index.html

Partial fix for #1505.
This does not address the root of the problem:
- We still need to identify what was/is corrupting the vic tar.
- Hopefully, since we now keep a backup of the original vic tar, this error won't occur. But that's not guaranteed. 
- Error message provided to the user is helpful but not actionable.

Always start fileserver regardless of configure errors

---

installer/build/scripts/systemd/scripts/vic-appliance-tls.sh

Auto conversion of PKCS1 to PKCS8 private key was in the wrong place.
```
root@Photon [ ~ ]# journalctl -u !$
journalctl -u vic-appliance-tls
-- Logs begin at Tue 2018-04-10 18:11:33 UTC, end at Tue 2018-04-10 18:15:52 UTC. --
Apr 10 18:12:00 Photon systemd[1]: Starting VIC Appliance TLS Certificate...
Apr 10 18:12:00 Photon vic-appliance-tls.sh[763]: TLS certificate, private key, and CA certificate are set, using customized certificate
Apr 10 18:12:00 Photon vic-appliance-tls.sh[763]: Private key /storage/data/certs/server.key is not in PKCS8 format
Apr 10 18:12:00 Photon vic-appliance-tls.sh[763]: Converted /storage/data/certs/server.key to PKCS8
Apr 10 18:12:00 Photon vic-appliance-tls.sh[763]: creating java keystore with user provided cert
Apr 10 18:12:00 Photon …
```

Fix usage of user provided TLS certs

---

installer/build/bootable/build-base.sh
installer/build/scripts/systemd/scripts/support/appliance-support.sh
installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh

Adds `--embedded-psc` to skip external PSC prompts
Adds `--appliance-password` for old appliance password
Adds `--fingerprint` for GOVC format vCenter fingerprint
Adds `--ssh-insecure-skip-verify` to skip host key checking for old appliance SSH
Adds `--appliance-version` for expected old appliance version. Exits install if expected != actual

Appliance upgrade non-interactive flags

---

installer/build/scripts/systemd/scripts/psc/get_token.sh

Fixes #1615 
Checks perms and owner before setting them to prevent systemd from triggering for file modifications.

Fix services restarting on token timer

---

installer/build/scripts/harbor/configure_harbor.sh
installer/build/scripts/systemd/scripts/psc/get_token.sh

After ca.crt and tokens.properties are copied to Harbor's directory the owner changed to root.
This PR changes the owner to 10000:10000 after it's copied.
This fixes the build issue in master branch.

Change owner of CA certificate and token file after they are copied to Harbor

---

dinv/README.md

When using a separate network connection, `vmware/dch-photon` doesn't work unless the port mappings are defined.
This may be a bug `vmware/dch-photon` or VIC. (Even if that's the case, then we should still have working documentation in the meantime.)

Added required port mapping for DCH

---

installer/build/bootable/config/builder.ovf
installer/build/scripts/systemd/scripts/vic-appliance-environment.sh
installer/docs/BUILD.md
installer/fileserver/server.go
installer/fileserver/tasks.go

Rename ovf keys for registry port

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-8-DRS.robot

I forgot to update this when I merged my upgrade tests PR, which renamed the keyword.

Fix keyword in DRS nightly test

---

installer/build/scripts/systemd/scripts/support/appliance-support.sh

Old way wan't working
Now:
```
root@Photon [ /etc/vmware/support ]# ./appliance-support.sh
Running cat /etc/vmware/environment
Removing APPLIANCE_TLS_PRIVATE_KEY from /tmp/vic_appliance_logs_2018-04-30-15-22-03/appliance/environment
Removing DEFAULT_USERS_DEF_USER_PASSWORD from /tmp/vic_appliance_logs_2018-04-30-15-22-03/appliance/environment
Running hostnamectl
Running timedatectl
Running ip address show
...
cat appliance/environment
VIC_MACHINE_SERVER_PORT=8443
APPLIANCE_SERVICE_UID=10000
HOSTNAME=10.160.0.145
IP_ADDRESS=10.160.0.145
ADMIRAL_PORT=8282
REGISTRY_PORT=443
NOTARY_PORT=4443
FILESERVER_PORT=9443
APPLIANCE_TLS_CERT=
APPLIANCE_TLS_CA_CERT=
DEFAULT_USERS_CREATE_DEF_USERS=True
DEFAULT_USERS_DEF_USER_PREFIX=vic
REGISTRY_GC_ENABLED=False
APPLIANCE_PERMIT_ROOT_LOGIN=True …
```

Filter private values in appliance support bundle

---

installer/build/scripts/provisioners/provision_harbor.sh

Fixes #1667 
docker-compose.yml
```
networks:
harbor:
external: false
services:
adminserver:
container_name: harbor-adminserver
depends_on:
- log
env_file:
- ./common/config/adminserver/env
image: vmware/harbor-adminserver:v1.5.0
logging:
driver: syslog
options:
syslog-address: tcp://127.0.0.1:1514
tag: adminserver
networks:
- harbor
restart: on-failure
volumes:
- /storage/data/harbor/config/:/etc/adminserver/config/:z
- /storage/data/harbor/secretkey:/etc/adminserver/key:z
- /storage/data/harbor/:/data/:z
jobservice:
container_name: harbor-jobservice
depends_on:
- redis
- ui
- adminserver
env_file:
- ./common/config/jobservice/env
image: vmware/harbor-jobservice:v1.5.0
logging:
driver: syslog
options:
syslog-address: tcp://127.0.0.1:1514
tag: jobservice
networks:
- harbor
restart: always …
```

Use restart policy always for Harbor jobservice

---

installer/build/scripts/upgrade/upgrade.sh

Fixes `--destroy` flag and log output 
```
root@Photon [ /etc/vmware/upgrade ]# ./upgrade.sh --target 10.160.140.175 --password 'Admin!23' --username 'administrator@vsphere.local' --dc ha-datacenter --fingerprint '10.160.140.175 49:8C:56:6B:F0:E6:54:D1:3F:77:4A:81:DE:BD:61:8B:80:CE:DF:E6' --appliance-username root --appliance-password password --appliance-target 10.192.49.135 --appliance-version v1.3.1 --destroy  --embedded-psc --ssh-insecure-skip-verify
-------------------------------
VIC Appliance Upgrade to v1.4.0
-------------------------------
2018-05-01 19:38:01 [=] Values containing $ (dollar sign), ` (backquote), \' (single quote), " (double quote), and \ (backslash) will not be substituted properly.
2018-05-01 19:38:01 [=] Change any input (passwords) containing these values …
```

Fix upgrade script variable

---

docs/user_doc/vic_vsphere_admin/deploy_vch_client.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/restart_services.md
docs/user_doc/vic_vsphere_admin/security_reference.md
docs/user_doc/vic_vsphere_admin/service_status.md

While checking the services running in the RC2 OVA, I noticed that the doc misnames the `vic-machine-server.service`.
@zjs has this name always been wrong in the docs, or did it change in 1.4? Thanks!

Corrected name of vic-machine-server.service

---

installer/build/scripts/harbor/configure_harbor.sh

As for Harbor DB migrates to pgsql, the clair DB needs to share the same password with harbor DB. This commit is to fix it in vic env.

unify harbor db and clair db password in first boot

---

installer/build/build-cache.sh

Caches the harbor registry image in the
vic appliance ova. Fixes #1712.
Fixes #

Cache harbor registry images (#1713)

---

tests/robot-run.sh
tests/vic-product-nightly.sh

Turns on verbose for `pabot` which makes it convenient to read logs directly on drone and jenkins UI.

Verbose output from pabot commands

---

.drone.yml

Fixes #1711 + created a new GCS bucket `vic-product-failed-builds` and verified drone can publish to it.

Add drone step to publish failed builds

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance_manual.md

Doc fix for https://github.com/vmware/vic-product/issues/1731. @morris-jason can you please review? Thanks! I also noticed that the examples included the appliance address in the `--target` option, which I have corrected to the VC address.

Specified that upgrade script doesn't support FQDN.

---

installer/build/bootable/root/etc/systemd/journald.conf.d/10-persistent.conf
installer/build/scripts/provisioners/provision_harbor.sh
installer/build/scripts/systemd/scripts/support/appliance-support.sh

Removes journal logsize limit, restricts Clair cpu usage, and adds kernel debugging logs to the appliance support bundle.
Fixes #1805
Request for 1.4.1 cherry pick.

Fix Clair CPU Restrictions

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh
tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.0.md
tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.0.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.4.0.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.4.0.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Fixes #1806.
Adds Manual and Automated Nightly upgrade tests for ova upgrade.
Adds 1.4.0 as a valid upgrade version for v1.4.1.
Request for 1.4.1 cherry pick.

Update upgrade script for 1.4.1

---

installer/docs/BUILD.md

Update all links to the Drone server we use for continuous integration testing to refer to the new server.

Update CI links in build documentation

---

.drone.yml

(cherry picked from commit d38d3302d3e66344d8e5a2c299beb23a584850ac)
---
Cherry picks: <d38d3302d3e66344d8e5a2c299beb23a584850ac>
From PR: #1736

Cherry-pick: Add drone step to publish failed builds (#1736)

---

installer/build/bootable/build-disks.sh
installer/build/bootable/build-main.sh

The builder OVF used to construct the OVA has hard-coded disk sizes. Correct these to match the final size of the VMDKs to avoid warnings during the OVA deployment process.
Fixes #1166

Use correct VMDK sizes when building OVA

---

.drone.yml
installer/build/bootable/build-disks.sh
installer/build/bootable/build-main.sh
installer/build/bootable/config/builder.ovf
installer/build/build-ova.sh
installer/build/container/Dockerfile
installer/build/scripts/harbor/configure_harbor.sh
installer/build/scripts/systemd/scripts/vic-appliance-environment.sh
installer/build/scripts/upgrade/upgrade.sh
installer/docs/BUILD.md
installer/docs/RELEASE.md
installer/fileserver/server.go
installer/fileserver/tasks.go
installer/scripts/ci-build.sh

(Note: This _must_ be submitted with the "rebase & merge" option, _not_ "squash & merge".)
Cherry-pick a variety of work from `master` to `releases/1.4.1` to include in 1.4.1-rc1. This should be a series of independent PRs, but I'm posting this all at once to allow a quicker turn-around cycle.
Cherry picks:
* 20bd476d from PR #1637
* 7c07bfe0 from PR #1642
* c7c1598b from PR #1685
* 49623c76 from PR #1684
* 6bbb3a7b from PR #1704
* 914d6066 from PR #1693
* 7a3d8471 from PR #1726
---

Cherry-pick a variety of changes into 1.4.1

---

installer/build/scripts/systemd/units/reconfigure_token.service

Add `RemainAfterExit=yes` to prevent `reconfigure_token` from running twice during initialization.
---

Avoid running reconfigure_token twice

---

installer/Makefile
installer/build/build.sh
installer/scripts/version-linker-flags.sh

The GitHub release process creates lightweight tags, which do not have
associated metadata such as date information. This causes git describe
to fall back to lexicographic ordering to break the tie between two or
more candidate tags when multiple exist on a given commit.
When building a new RC build to pick up a new RC build of a component,
we wind up with multiple tags on a single commit in vic-product (since
we simply need to do a new build of the same commit to pick up the new
build of the changed component).
When we are performing a tag build, we expect the corresponding tag to
be used— which may not always be the tag that would be selected by git
describe. Ensure we use the expected tag falling back to git describe
only if the $DRONE_TAG variable is not set.
This should preserve the …

Handle multiple lightweight tabs on a commit

---

installer/Makefile
installer/build/build.sh
installer/scripts/version-linker-flags.sh

The GitHub release process creates lightweight tags, which do not have
associated metadata such as date information. This causes git describe
to fall back to lexicographic ordering to break ties between candidate
tags when multiple exist on a given commit.
When building a new RC build to pick up a new RC build of a component,
we wind up with multiple tags on a single commit in vic-product (since
we simply need to do a new build of the same commit to pick up the new
build of the changed component).
When we are performing a tag build, we expect the corresponding tag to
be used— which may not always be the tag that would be selected by git
describe. Ensure we use the expected tag falling back to git describe
only if the $DRONE_TAG variable is not set.
This should preserve the current …

Cherry-pick: Handle multiple lightweight tabs on a commit (#1858)

---

installer/scripts/version-linker-flags.sh

When replacing the tag command with an environment variable, the
surrounding backticks were not removed.
This was not caught during testing because the script did not return
a non-zero exit code, even though an error had occurred. Add a set
line to prevent similar errors from going undetected in the future.
---

Remove erroneous backticks in linker flags 

---

installer/scripts/version-linker-flags.sh

When replacing the tag command with an environment variable, the
surrounding backticks were not removed.
This was not caught during testing because the script did not return
a non-zero exit code, even though an error had occurred. Add a set
line to prevent similar errors from going undetected in the future.
(cherry picked from commit 658a40893d23a6184b41340118982f4321cc5be4)
---
Cherry picks: 658a40893d23a6184b41340118982f4321cc5be4
From PR: #1861

Cherry-pick: Remove erroneous backticks in linker flags (#1861)

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_app_dev/configure_docker_client.md
docs/user_doc/vic_cloud_admin/SUMMARY.md
docs/user_doc/vic_cloud_admin/add_vch_fullTLS_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_noTLS_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_serversideTLS_in_portal.md
docs/user_doc/vic_cloud_admin/content_trust.md
docs/user_doc/vic_cloud_admin/manage_projects.md
docs/user_doc/vic_cloud_admin/vchs_and_mgmt_portal.md
docs/user_doc/vic_cloud_admin/working_with_projects.md
docs/user_doc/vic_overview/intro_to_vic_registry.md
docs/user_doc/vic_vsphere_admin/vch_registry.md

Fixes https://github.com/vmware/vic-product/issues/1688.
Related to https://github.com/vmware/vic-product/issues/1659 in that I think that we should recommend against adding the same VCH to more than one project.
@zjs @hickeng can you please review? Thanks!

Documented how content trust affects VCHs

---

installer/build/scripts/upgrade/upgrade.sh

Because v1.2.1 had a different disk topology than v1.3.0 and later, it
requires a slightly different upgrade process. This was handled by
explicitly checking whether the "source" version is v1.3.0 or v1.3.1
and moving the new disks only in those cases.
We expect the disk topology to remain consistent until an intentional
change is made. Reverse the conditional logic to disable the v1.3.0+
logic only when the version is v1.2.1. (Upgrade from earlier versions
is unsupported, and an error is returned if attempted.)
This causes upgrade from v1.4.0 to behave like upgrade from v1.3.x and
ensures that support for upgrade from future v1.4.x patches can easily
be added without needing to update several places in this file.
---
If this is a feature or change to existing …

Revise upgrade script to treat v1.4.0 like v1.3.x

---

installer/build/scripts/upgrade/upgrade.sh

Because v1.2.1 had a different disk topology than v1.3.0 and later, it
requires a slightly different upgrade process. This was handled by
explicitly checking whether the "source" version is v1.3.0 or v1.3.1
and moving the new disks only in those cases.
We expect the disk topology to remain consistent until an intentional
change is made. Reverse the conditional logic to disable the v1.3.0+
logic only when the version is v1.2.1. (Upgrade from earlier versions
is unsupported, and an error is returned if attempted.)
This causes upgrade from v1.4.0 to behave like upgrade from v1.3.x and
ensures that support for upgrade from future v1.4.x patches can easily
be added without needing to update several places in this file.
(cherry picked from commit a9cb0c450b596f3d0df9585102b9c68e930d8168)
--- …

Cherry-pick: Revise upgrade script to treat v1.4.0 like v1.3.x (#1869)

---

installer/build/scripts/systemd/units/reconfigure_token.service

This reverts commit 30849e4ab545ef351d63231b7542a7eb78aec7d1, which
breaks the "Re-initialize the vSphere Integrated Container Appliance"
operation on the "Getting Started" page.
For more information, see https://github.com/vmware/vic-product/pull/1840#issuecomment-401127179.
---

Revert "Avoid running reconfigure_token twice (#1849)"

---

.drone.yml
installer/docs/RELEASE.md

As documented in `installer/docs/RELEASE.md`, our process is to include filesize and checksum information when publishing a release on GitHub.
Output that information in a structured way during the build process to ensure that accurate information can be easily posted.
Include this output for all published builds to allow integrity to be verified in all cases.
---

Print file size and checksums before publishing

---

docs/user_doc/vic_vsphere_admin/plugins_vcsa.md

To ensure that only the intended file is deleted by the administrator,
refer to it explicitly (using the environment variable set earlier in
the installation process) instead of via a wildcard that could match
other .tar.gz files in the same directory.

Clarify cleanup process following OVA installation

---

.drone.yml
installer/build/bootable/build-disks.sh
installer/build/bootable/build-main.sh
installer/build/build-ova.sh
installer/build/build.sh
installer/build/scripts/harbor/configure_harbor.sh
installer/build/scripts/systemd/scripts/psc/get_token.sh
installer/docs/BUILD.md
installer/docs/RELEASE.md

Cherry-pick:
* Change owner of CA certificate and token file after they are copied. (d42c6d9 from #1630)
* Use correct VMDK sizes when building OVA (62bccb8 from #1831)
* Output reminder for next step of release process (840ed86 from #1860)
* Print file size and checksums before publishing (4459076 from #1867)

Initial cherry-picks for 1.4.2

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Updates upgrade scripts to list 1.4.1 as a supported upgrade path.
---
Fixes: #1886

Update upgrade scripts for 1.4.2

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Updates upgrade scripts to list 1.4.1 as a supported upgrade path.
---
Cherry picks: e811e0afa23a2302f46a94b6b3b422918700ca28
From PR: #1884

Cherry-pick: Update upgrade scripts for 1.4.2 (#1884)

---

installer/build/build-ova.sh

For some reason, `head -n1` is resulting in exit code 141 despite being protected by `trap '' PIPE`. This same pattern is used successfully in the preceding logic. It is not clear why we are seeing this issue now, or why trap is not behaving as expected.
Disabling pipefail for this line is acceptable because the build does not even use the results of this line on the release branch.
Note: This change should be reverted once the cause is understood.

Work around inexplicable pipe error during build

---

installer/build/scripts/upgrade/upgrade.sh

The commit (e811e0afa23a2302f46a94b6b3b422918700ca28) to add upgrade support from 1.4.2 omitted a right bracket. This mistake caused upgrade to fail from 1.4.0.
---

Add missing right bracket to upgrade script

---

installer/build/scripts/upgrade/upgrade.sh

By default, govc vm.disk.attach "links" disks, which sets their disk
mode to independent. Disable this flag to ensure attached disks are
dependent disks, so that snapshots can be taken.
---
Fixes #1885

Do not link disks when attaching during upgrade

---

installer/build/scripts/upgrade/upgrade.sh

The commit[1] to add upgrade support from 1.4.2 omitted a right
bracket. This mistake caused upgrade to fail from 1.4.0.
1 - e811e0afa23a2302f46a94b6b3b422918700ca28
(cherry picked from commit 10aa9d492576660c925a2a1ede5a649432792bba)
---
Cherry picks: 10aa9d492576660c925a2a1ede5a649432792bba
From PR: #1890

Cherry-pick: Add missing right bracket to upgrade script (#1890)

---

installer/build/scripts/upgrade/upgrade.sh

By default, govc vm.disk.attach "links" disks, which sets their disk
mode to independent. Disable this flag to ensure attached disks are
dependent disks, so that snapshots can be taken.
(cherry picked from commit f87e94f05ddad9f0047861f4358d90e8bf0a91e1)
---
Cherry picks: f87e94f05ddad9f0047861f4358d90e8bf0a91e1
From PR: #1889

Cherry-pick: Do not link disks when attaching during upgrade (#1889)

---

tutorials/elasticsearch/Readme.md
tutorials/elasticsearch/docker-compose.yml

- [* ] Up to date with `master` branch
Also in Readme:
1. To provide flexibility for elastic/server admins to bring up additional elasticsearch container nodes on VIC dvSwitch mapped subnets. 
2. This configuration will also provide an avenue for moving from non-containerized elasticsearch clusters to a fully containerized configuration. 
**Please keep in mind that part of the 'magic' with this configuration is utilizing Named Volumes. Compose does not remove named volumes when performing docker-compose down. This is crucial to allowing the transition to container nodes.**
---
The hosts referred to as **'log'**, **'elk-node1'**, **'elk-node2'** in this compose file are current elasticsearch nodes being prepped for containerization; Once the cluster has …

Cdinkens elasticsearch tutorial

---

installer/docs/RELEASE.md

Explicitly document information about the importance of git tags and
branches that was previously assumed to be common knowledge.
---

Add overview to release documentation

---

installer/build/build-ova.sh

Update the conditional to use the correct value for DRONE_BUILD_EVENT.
The command is `drone deploy`, but the build event is "deployment".
This value is not documented in Drone's environment reference:
http://readme.drone.io/usage/environment-reference/
---

Fix reminder logic for staging builds

---

.drone.yml
tests/vic-product-nightly.sh

Because builds from all branches are written to the same directory,
it is difficulty to pick up the right build to test against different
release branches.
Publish artifacts from release branches into sub-directories of a
releases directory, so nightly test of a release branch can select the
last build artifact under the subdirectory for testing.
Tags builds are published to a "tags" directory.
Fixes #

Publish artifacts from release branches separately

---

tests/resources/page-objects/New-Container-Host-Modal-Util.robot
tests/resources/page-objects/Verify-Certificate-Modal-Util.robot

this pr try to fix the ci build error, becasue the new container host ui changed from a dialog to current page.
The robot selector should also change.
Fixes #

fix vic product ci can not find 'New Container Host' title

---

tests/vic-product-nightly.sh

Remove the needless slash in gs path.
Add parameters to run robot tests.
Fixes #

Enhance the nightly script

---

.drone.yml
dinv/ci.sh
dinv/dch-photon-1.12/main.go
dinv/dch-photon-1.13/main.go
dinv/dch-photon-17.06/main.go
tests/resources/VCH-Util.robot
tests/test-cases/Group5-DCH/5-01-DCH.md
tests/test-cases/Group5-DCH/5-01-DCH.robot
tests/test-cases/Group5-DCH/Testcases.md
tests/test-cases/TestGroups.md

dcp-photon image could accept a parameter '--tlsverify', it means
tlsverify mode is enabled for docker deamon, but in current dcp-photon
image, it does not enable the tlsverify mode. This patch is validated
in my local env.
Fixes #1903

Support tlsverify for dch-photon image

---

docs/user_doc/vic_app_dev/photon_cert_manual.md

The example is intended to be used with the default dch-photon image that comes with the VIC Appliance which has only the tag "1.13" by default. The "-cert" is not needed in this example and should be removed.
Fixes #

Remove "-cert" from the image tag used in the create example

---

installer/docs/BUILD.md

The way we determine the build of each dependency to consume depends
on both on the way the dependency's artifacts are published and the
type of build being performed. Document the current behavior in
preparation for proposing changes.
Additionally, document the variety of locations where the OVA may be
published depending on the type and results of the build.
---
* N/A
* N/A
* N/A

Document dependency consumption per build type

---

installer/fileserver/server.go
installer/lib/tls.go

In order to protect the Getting Started page from being embedded in a page controlled by an attacker, set the Content-Security-Policy header to disallow rendering of the page within an iframe.
---
* There are currently tests which interact with the Getting Started page using Selenium, but there doesn't seem to be a keyword to inspect the HTTP headers, so adding a test for this might be a large change.
* This does not seem like something we'd need to document.
Fixes #1512

Prevent fileserver from being loaded in an iframe

---

tests/resources/OVA-Util.robot

The output text of curl includes numbers and sometimes http code
like number 200 or 302 is in it.
Use silent mode to get just http code from curl.
Fixes #1936

Fix curl option to get http code

---

.drone.yml

Currently, producing an OVA build on the feature branch is a manual
process. Include feature branches in Drone automation. Consume
dependencies from them as if they were the master branch (as that is
the branch feature branches are based on).
---
* N/A
* Upgrade between builds from `master` and feature branches is unlikely to work properly, but that's no worse than PR builds.
* N/A
* N/A

Build and test work on feature branches via CI

---

installer/build/bootable/build-base.sh

The latest package initramfs-1.0-9.113018881.ph1.x86_64 requires
linux = 4.4.147-1.ph which can not be found in photon repository.
As a workround previous version initramfs-1.0-9.113016321.ph1 can
be installed.

Fix initramfs dependency package missing

---

installer/build/bootable/build-base.sh

A mistake made before is installing initramfs to build machine.
It should be installed to the root file system of vmdk.
Fixes #1969

Fix initramfs not installed to vmdk

---

installer/docs/BUILD.md
installer/scripts/ci-build.sh
tests/resources/page-objects/New-Container-Host-Modal-Util.robot
tests/resources/page-objects/Verify-Certificate-Modal-Util.robot

Consuming only tagged components in non-dev tag builds ensures that
our release candidates and releases include only the expected, stable,
version of each component.
Consuming those same tagged components in push and pull_request builds
is beneficial because it maintains consistency between builds leading
up to a tag build and the tag build itself.
However, this has a significant disadvantage: it means that components
being developed on release branches concurrently are not continuously
integrated; the first time integration occurs is when RC1 is tagged.
To allow testing of OVA builds sooner, we can consume new versions of
components more aggressively for pull_request builds, push builds, and
dev tag builds.
For Admiral, we will consume the same vic_dev tag consumed on master.
For the VIC …

Cherry-pick: Integrate pre-tag components in release builds (#1961) 

---

installer/build/bootable/build-base.sh

The latest package initramfs-1.0-9.113018881.ph1.x86_64 requires
linux = 4.4.147-1.ph which can not be found in photon repository.
As a workround previous version initramfs-1.0-9.113016321.ph1 can
be installed
Fixes #1976

Cherry-Pick: Fix initramfs dependency package missing

---

installer/build/build-ova.sh

Update the conditional to use the correct value for DRONE_BUILD_EVENT.
The command is `drone deploy`, but the build event is "deployment".
This value is not documented in Drone's environment reference:
http://readme.drone.io/usage/environment-reference/
(cherry picked from commit 9b6ab3f5bb97c85aeb6fd524141f20731803532f)
---
Cherry picks: 9b6ab3f5bb97c85aeb6fd524141f20731803532f
From PR: #1893

Cherry-pick: Fix reminder logic for staging builds (#1893)

---

installer/build/container/Dockerfile

Include diff in the vic-product-build image as it is required for use
by goimports to report errors. Without it, the build fails with a
confusing message if an import ordering issue exists:
checking gofmt...
computing diff: exec: "diff": executable file not found in $PATH
Makefile:69: recipe for target 'gofmt' failed
---
* N/A
* N/A
* N/A
* N/A
* N/A

Add diff to image for goimports error reporting

---

docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md

Fixes https://github.com/vmware/vic-product/issues/1967. Clarifies which bundle to use for plug-in installation, and provides copy/pastable commands.

Clarified VIC Engine bundle version for plugins

---

tests/resources/OVA-Util.robot

The output text of curl includes numbers and sometimes http code like number 200 or 302 is in it.
Use silent mode to get just http code from curl.
(cherry picked from commit ead265b84b8f3ce445436dbad57a377074964dd8)
---
Cherry picks: ead265b84b8f3ce445436dbad57a377074964dd8
From PR: #1962

Cherry-pick: Fix curl option to get http code (#1962)

---

installer/fileserver/server.go
installer/lib/tls.go

In order to protect the Getting Started page from being embedded in a
page controlled by an attacker, set the Content-Security-Policy header
to disallow rendering of the page within an iframe.
(cherry picked from commit a9f8389878bd164003ca33ded18ce3a53e2a86df)
---
Cherry picks: a9f8389878bd164003ca33ded18ce3a53e2a86df
From PR: #1907

Cherry-pick: Prevent fileserver from being loaded in an iframe (#1907)

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Updates upgrade scripts to list 1.4.2 as a supported upgrade path.
---
* N/A
* N/A

Update upgrade scripts for 1.4.3

---

.drone.yml

Leverage the drone-slack plugin's template functionality to provide
more useful notifications about completed builds. Reduce duplication
between pipeline steps for successful and failed builds.
---
Example notifications:
Eventually, I'd like to find a way to distinguish between "original" builds, builds restarted by the downstream trigger, and manually-restarted builds. However, I was not able to find a way to do so.
---

Improve and deduplicate slack notifications

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Updates upgrade scripts to list 1.4.2 as a supported upgrade path.
(cherry picked from commit 1b0ba93ca9b1a396dbc38ebbf66709a194434924)
---
Cherry picks: 1b0ba93ca9b1a396dbc38ebbf66709a194434924
From PR: #1954

Cherry-pick: Update upgrade scripts for 1.4.3 (#1954)

---

tutorials/api/README.md

A tutorial on the use of the VCH Management API was written while the API was under development for 1.3.0 and includes a variety of stale information as a result. The tutorial is still a useful starting point
for users interested in providing feedback on the API. Update instructions and documentation links to be relevant for 1.4.x.
---

Update VCH Management API tutorial for 1.4

---

installer/build/bootable/build-base.sh

Setting initramfs to an old version is a workaround
for missing dependency package in remote repository.
Revert this to install latest version since remote
repository fix this issue.
Fixes #

Revert initramfs to latest version

---

installer/build/bootable/build-base.sh

Setting initramfs to an old version is a workaround
for missing dependency package in remote repository.
Revert this to install latest version since remote
repository fix this issue.
(cherry picked from commit 3e6eee2c098ffa2acfed87ca15696c03fef2d7e4)
---
Cherry picks: 3e6eee2c098ffa2acfed87ca15696c03fef2d7e4
From PR: #1986

Cherry-pick: Revert initramfs to latest version (#1986)

---

tests/resources/Nimbus-Util.robot

vSphere requires 'datacenter/host/cluster' format for access path.
ovftool failed to find the target if only specify 'cluster'
Fixes #

[WIP]Fix wrong TEST_RESOURCE path.

---

installer/fileserver/html/index.html

VIC appliance UI plugin is registered automatically during
initialization, so there is no need to direct users to the
document link to install manually any more.
Fixes #1942

Remove page link to install vSphere client plugin

---

installer/fileserver/html/index.html

VIC appliance UI plugin is registered automatically during
initialization, so there is no need to direct users to the
document link to install manually any more.
(cherry picked from commit d75808f3205dc5332e0f1555eb7d8143705841c6)
Fixes #1942 
Cherry picks: d75808f3205dc5332e0f1555eb7d8143705841c6
From PR: #2003

Cherry-pick: Remove page link to install vSphere client plugin (#2003)

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-05-Enhanced-Linked-Mode.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-06-2-VSAN-Complex.disabled
tests/manual-test-cases/Group5-Interoperability-Tests/5-09-Network-Folder.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-16-vMotion-VCH-Appliance.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-17-FC-Datastore.robot
tests/resources/Nimbus-Util.robot
tests/resources/nimbus-testbeds/ELM-DRS-Disabled.robot

If omitting the ESX and vCenter version parameters to the Nimbus Testbed
Deploy keyword we get arguments to the underlying script being position
shifted and causing confusing output/failures.
This quotes the provided strings to ensure that even if empty we keep
the argument positions when calling the underlying scripts.
Towards #1957

Quote potentially empty param to nimbus keyword

---

tests/resources/Nimbus-Util.robot

Remove nimbus location to get assigned location from nimbus.
This fix deliverables of esx build 5050593 not found in wdc.
This is crossport from vic #8256.
Fixes #

Remove specifying nimbus location

---

installer/build/scripts/provisioners/provision_fileserver.sh

Some versions include '-' which will fail

Change vic ui version string to remove prefix

---

installer/fileserver/html/index.html

Signed-off-by: Meina Zhou <meinaz@vmware.com>
In thumbprint page. click "Read more link" will redirect to a new page, which is not good for ux point of view. 
Fixes #
add target attribute to open url in new tab.

read me document will open another tab page

---

installer/build/scripts/provisioners/provision_fileserver.sh

.zip files will be used to serve plugins, and there is no need to
keep vic_ui*.tar.gz any more.

Remove vic_ui*.tar.gz from fileserver

---

tests/resources/Nimbus-Util.robot

vSphere requires 'datacenter/host/cluster' format for access path.
ovftool failed to find the target if only specify 'cluster'
This will fix 2-05-Static-IP failures.
(cherry picked from commit afb284ec9b110a2db197888a9d05408ae2252bb9)

[Cherry-pick]Fix wrong TEST_RESOURCE path for 2-05-Static-IP (#1993)

---

installer/build/scripts/provisioners/provision_fileserver.sh

.zip files will be used to serve plugins, and there is no need to
keep vic_Ui*.tar.gz any more.
(cherry picked from commit d6e5e9895fc6c2ce943fe116745648c975bc8808)

Cherry-pick: Remove vic_ui*.tar.gz from fileserver (#2034)

---

tests/resources/Nimbus-Util.robot

Remove nimbus location to get assigned location from nimbus.
This fix deliverables of esx build 5050593 not found in wdc.
This is crossport from vic #8256.
(cherry picked from commit c9b06a2537fed01c43bbc7bb5d42276e21c99e07)
Fixes #

Cherry-Pick: Remove specifying nimbus location (#2022)

---

.drone.yml

Leverage the drone-slack plugin's template functionality to provide
more useful notifications about completed builds. Reduce duplication
between pipeline steps for successful and failed builds.
(cherry picked from commit 21bd1034ecb3121c55a3085a6507dabadcab610b)
---
Cherry picks: 21bd1034ecb3121c55a3085a6507dabadcab610b
From PR: #1983

Cherry-pick: Improve and deduplicate slack notifications (#1983)

---

installer/docs/BUILD.md
installer/docs/RELEASE.md

Update document to reflect vic ui build change

---

installer/build/scripts/upgrade/upgrade.sh

Because both the `payload` and `payload_info` variables were quoted with
single quotes, expressions were not being expanded.
Correct the quoting to properly print the JSON object; wrap constant
portions of the JSON with single quotes and expressions with double.
---
* I don't see a good way to do this, unfortunately.
Fixes: #2050 (see https://github.com/vmware/vic-product/issues/2050#issuecomment-420404212 for results of testing)

Fix quoting of registration payload in upgrade.sh

---

installer/build/scripts/upgrade/upgrade.sh

When manually moving disks, we don't need the old VM's datacenter, username, password, or IP address (and we can't properly destroy the appliance at the end of the process). Update the input prompts, help text, and control flow to reflect this.
---
* I don't see a good way to do this, unfortunately.
Related: #2021

Simplify upgrade.sh input for manual disk move

---

installer/build/scripts/upgrade/upgrade.sh

When manually moving disks, we don't need the old VM's datacenter,
username, password, or IP address (and we can't properly destroy the
appliance at the end of the process). Update the input prompts, help
text, and control flow to reflect this.
(cherry picked from commit 7d7bbb3eeee9de6e30fb0e67377d58a2b03292c0)

Simplify upgrade.sh input for manual disk move (#2054)

---

installer/build/scripts/upgrade/upgrade.sh
tests/resources/OVA-Util.robot

Fix an issue in script mode too: --fingerprint includes vCenter address,
and we need to remove vCenter address part before passing it to
registration/plugin api.
(cherry picked from commit fa31e1cd821a80e7076cfc9a0d3df6b1aa5e3a23)

Cherry-pick: Add upgrade-ui-plugin option to nightly test (#2048)

---

tests/manual-test-cases/Group9-VIC-UI/9-2-VIC-UI-Uninstaller.robot

Comment out flex plugin uninstall case because flex installation
on vCenter 6.7 is not supported currently.

Fix Group9-VIC-UI test failure

---

installer/fileserver/routes/register.go

The register rest api does not read external psc information
from request, and always use vc information. There is no way
to use an external psc for registeration from api, such as
during upgrade without the fix.

Add missing external psc information into register

---

installer/fileserver/routes/register.go

The register rest api does not read external psc information
from request, and always use vc information. There is no way
to use an external psc for registeration from api, such as
during upgrade without the fix.
(cherry picked from commit 341ca9e0067f51faf3c6ea00f1323e16073bf3c6)

Cherry-pick: Add missing external psc information into register (#2091)

---

docs/user_doc/vic_vsphere_admin/bridge_network.md

As pointed out by @arslanabbasi via Slack, there was an extra `0` in the range.

Corrected IP range for bridge network

---

docs/user_doc/vic_app_dev/configure_docker_client.md

Hi @stuclem , I removed the note on FQDN from https://vmware.github.io/vic-product/assets/files/html/1.1/vic_app_dev/configure_docker_client.html 
Should I remove the line _The Create Virtual Container Host wizard only accepts an IP address for the client network. You cannot specify an FQDN._ from https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/client_network.html?
Fixes #323

Removed note about FQDN

---

.drone.yml
installer/build/scripts/provisioners/provision_fileserver.sh

Follow below rules to build 1.4.4 OVA:
1. Pack 1.4.3 vic and vic machine.
2. Pack 1.5.0 harbor. - using 1.5.4 version
3. Pack 1.4.3 admiral.
4. Pack vic-ui from 1.4.4 release branch.
Fixes #

Specify artifacts to build OVA

---

.drone.yml

Download harbor 1.5.4 from a full url instead of a link.
Fixes #

Use fixed harbor 1.5.4 archive url

---

.drone.yml
tests/resources/Util.robot
tests/resources/page-objects/Container-Hosts-Page-Util.robot
tests/resources/page-objects/New-Container-Host-Modal-Util.robot
tests/resources/page-objects/VC-Single-Sign-On-Util.robot
tests/test-cases/Group2-Getting-Started/2-01-Getting-Started.robot
tests/test-cases/Group3-Admiral/3-01-Admiral-UI.robot
tests/test-cases/Group4-Harbor/4-01-Harbor.robot
tests/test-cases/Group5-DCH/5-01-DCH.robot

Rectify element locators according to below changes in UI:
1.Credentials dropdown list was changed to select.
2.Remove link was moved out of "Options" dropdown list.
Wait up to maximun 10 minutes for Admiral UI ready so we
don't need to retry failed tests.
Increase test timeout to 20 minutes since UI could not be
ready in 5 minutes.
Fixes #

Fix test failures caused by Admiral UI changes

---

.drone.yml
installer/build/bootable/build-app.sh
installer/build/bootable/build-base.sh
installer/build/bootable/repo/photon-local.repo
installer/build/bootable/repo/photon-remote.repo
installer/build/bootable/repo/photon-updates-local.repo
installer/build/bootable/repo/photon-updates-remote.repo
installer/build/bootable/repo/tdnf.conf
installer/build/build.sh
installer/build/container/Dockerfile
installer/build/container/push.sh

Use photon 2.0 image as build image.
Use local photon repository to install packages for CI build. Reset
remote repo afterward.
In photon 2.0, builtin toybox conflicts with many other packages
listed in Dockerfile. To avoid modify build scripts, remove toybox
and add packages for commands used to be provided by toybox.
locale-gen is broken in photon 2.0 so comment it out.
Fixes #2103

Move appliance OS to photon 2.0

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Updates upgrade scripts to list 1.4.4 as a supported upgrade path.

Update upgrade scripts for 1.5.0

---

installer/fileserver/html/css/style.css
installer/fileserver/html/index.html
installer/fileserver/html/js/index-handler.js
tests/resources/page-objects/Complete-Installation-Modal-Util.robot

fixed : vic-tasks-Appliance welcome page (9443) allows for external service interaction (HTTPS) without authentication #93
When re-initializing the VSPHERE integrated container appliance, Request to enter Vic appliance password
Signed-off-by: FangyuanCheng <fangyuanc@vmware.com>

Appliance Welcome page requires input of VIC appliance password

---

dinv/README.md
dinv/ci.sh
dinv/dch-photon-17.06/Dockerfile

Only docker 17.06 is available in Photon 2.0 repositoy, DCH 1.12 and
1.13 images will remain with Photon OS 1.0.
Set a DEBUG flag to CI build script for troubleshooting.
Fixes #2104

Move DinV to Photon OS 2.0

---

installer/build/scripts/admiral/start_admiral.sh
installer/build/scripts/vic-machine-server/vic-machine-server.service

Drop all capabilities of admiral.
Only enable NET_BIND_SERVICE capability of vic-machine-server.
Remove specifying UID option because it runs with non-root user
by default now.
Fixes #

Drop unused capabilities for containers

---

installer/build/scripts/systemd/scripts/vic-appliance-tls.sh

Decrease the validity period for auto-generated SSL certificates from 1095 days (3 years) to 825 days (27 months). This has little impact on the product or its users, but avoids potentially confusing false
positives from vulnerability scanners like Qualys. (A maximum validity period of 825 days applies to DV and OV certificates issued by CAs.)
---
* There does not seem to be a good way to test this.
* The negative impacts of regenerating certificates on users seem to outweigh any benefit to regenerating during upgrade.
* n/a - Doesn't seem to be mentioned.

Decrease validity period for generated certificates

---

installer/fileserver/html/index.html

While this setting is ignored by many modern browsers, its absence can still cause problems when obtaining PCI compliance.
---
* n/a - Doesn't seem to be mentioned.

Disable password autocomplete during initialization

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch-No-Cluster.robot
tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Due to GUI design of listing VCHs was changed to sort by IP address, so script '5-01-Distributed-Switch-No-Cluster' failed to locating the wanted VCH, it wants a VCH with property 'datastore' named 'datastore1', it always at the head of VCH nodes.
After design changed, the position of this VCH may not be at the head of the list, so add a 'if condition' in keyword 'Create VCH using UI And Set Docker Parameters' to locate VCH index by '1' or IP address.
Fixes #2220

Modify ways to identify host from css to xpath by host IP

---

installer/build/build-ova.sh
installer/build/scripts/provisioners/provision_harbor.sh
installer/build/scripts/upgrade/upgrade-harbor.sh

Latest DCH is 17.06 so pack it into Harbor as a default image.
Harbor was moved from vmware/harbor to goharbor/harbor.

Update out of date build script

---

.drone.yml

Pack Harbor 1.7.0 RC1 artifact into VIC 1.5.0.

Use Harbor 1.7.0 RC1 for VIC 1.5.0

---

installer/build/bootable/config/builder.ovf
installer/build/scripts/provisioners/system_settings.sh
installer/build/scripts/systemd/scripts/ntp-config.sh
installer/build/scripts/systemd/scripts/vic-appliance-environment.sh
installer/build/scripts/systemd/units/ovf-ntp.service
installer/build/scripts/systemd/units/vic-appliance-environment.service
installer/build/scripts/systemd/units/vic-appliance-ready.target
installer/ovatools/vic-ova-ui/main.go
installer/ovatools/vic-ova-ui/network_status.go

Allow user to specify NTP servers from VIC appliance deployment
wizard.
Fixes #1390

Enable NTP configurable

---

docs/user_doc/vic_vsphere_admin/ova_reg_api.md

Towards https://github.com/vmware/vic-product/issues/2160.
I will add the VIC password to the upgrade doc in a separate PR, because I have upgrade updates in progress in another branch.
@wjun is this OK? Thanks!

Added vicpassword to OVA registration API doc

---

installer/build/scripts/provisioners/provision_harbor.sh

Harbor configure https://vic_appliance_address to harbor portal UI,
which is only right on standalone mode. In VIC, it should redirects
to Admiral UI.
Fixes #2216

Redirect / to Admiral UI

---

.drone.yml

Latest release build tag is v1.4.3 and we need to pack v1.5.0 into
VIC appliance. We should revert this change once v1.5.0 is tagged.
Fixes #

Pack dev version of Admiral

---

.drone.yml
tests/wait_until_previous_builds_complete.sh

Hit failure when multi vic-product CI build run as parallel in Drone
Change to sequential for now
Revert it back to parallel when vic-product CI infra is ready
Address issue2260

Change vic-product CI run as sequential

---

.drone.yml

This reverts commit ad6f1b34612d69174574f672a8d442f35ff1049b.
Fixes #

Revert "Pack dev version of Admiral (#2255)"

---

dinv/dch-photon-17.06/Dockerfile

The default terminal is xterm which causes double prompts shown after
every command is issued. Change it to linux.
Fixes #

Fix showing double prompts in terminal

---

.drone.yml

Pack Harbor 1.7.1 into VIC appliance. This should be reverted
after 1.7.1 GA.
Fixes #

Pack temporary Harbor 1.7.1 build

---

installer/scripts/ci-build.sh

Options passed to ci-build.sh will be overwrote by admiral when it
is a tag event.
Fixes #

Fix admiral overwriting other options

---

installer/build/scripts/provisioners/provision_harbor.sh

in niginx config there is a 302 redirect for login
location ~ /$ {
return 302 https://\$host:8282\$request_uri;
}
it will block docker login. Should change to:
location ~ /$ {
return 302 https://\$host:8282\$request_uri;
}

fix harbor can not login

---

dinv/dch-photon-1.12/main.go
dinv/main.go
tests/test-cases/Group5-DCH/5-01-DCH.robot

dinv has a parameter -local, when it is specified, the dch-photon
will start dockerd with unix:///var/run/docker.sock. When local is
not specified, the dockerd will be started with tcp://0.0.0.0:xxx.
This change will enable unix:///var/run/docker.sock always.
Fixes #7316

Add local socket monitoring for dch-photon

---

.drone.yml

Update download url of Harbor to 1.7.1 GA build.
Fixes #

Update download url of Harbor 1.7.1

---

docs/user_doc/vic_vsphere_admin/volume_stores.md

Doc fix for https://github.com/vmware/vic/issues/8043. The regenerated HTML is in https://github.com/vmware/vic-product/pull/2244.
@YanzhaoLi and @zjs can you please review?
This change is only applicable to the 1.4 docs.

Doc fix for NFS volume stores

---

docs/user_doc/vic_vsphere_admin/interop.md

Fixes https://github.com/vmware/vic-product/issues/2176.
This change also needs to go into 1.4.x.

Removed workaround for Storage DRS

---

installer/build/scripts/provisioners/provision_fileserver.sh
installer/build/scripts/provisioners/provision_harbor.sh
installer/build/scripts/systemd/scripts/load-docker-images.sh

Clean up cache files to reduce disk space of VIC appliance OVA.
Fixes #2326

Clean up cache files

---

tests/test-cases/Group5-DCH/5-01-DCH.robot

In our testing, we sometime hit DCH docker daemon not running in our check point.
We add some sleep to wait it run.
In order not to miss critical issue, we only try at most 5 times with 3s
as intervals.
Fix issue #2079

Add sleep time to wait DCH docker daemon run

---

installer/build/scripts/provisioners/provision_fileserver.sh

Flex Client Plugin is already removed from vic-ui and should be removed
from build script.
Fixes #

Remove building Flex Client Plugin

---

.drone.yml

This reverts commit 791d25d5ec9daf7caf053ec6312e45115a339d2c. We
should get latest components in master branch.
Fixes #

Revert "Specify components for 1.5.1 release"

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Allow upgrade appliance from 1.5.0 and 1.5.1.
Skip harbor upgarde if the appliance version is lower than 1.5.0.
Fixes #

Support upgrade from 1.5.0 and 1.5.1

---

.drone.yml

Use Admiral 1.5.0 for VIC 1.5.2 release.
Fixes #

Use Admiral 1.5.0 for VIC 1.5.2 release

---

installer/build/scripts/upgrade/upgrade-harbor.sh

Since goharbor images has been packed into ova, the upgrader should
use harbor-provided offline image so that upgrade can work without
network connectivity and also can avoid hard-coding image version
Fixes #

Use offline harbor-migrator image

---

installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh

From VIC 1.5.0 Harbor handles db migration by itself so only
configuration migration is required for upgrade.
Fixes #

Only migrate Harbor configuration

---

.drone.yml

Change Harbor from 1.7.4 RC1 to GA build.
Fixes #

Pack Harbor 1.7.4 GA build

---

installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh

After copying disks from old appliance, vic-appliance.target is
started and dependent harbor.service start is also triggered. Although
stopping harbor.service is issued subsequently but harbor is not up
and it does not take effect. Backing up database files will fail if
DB container is up. Move function migrateHarborCfg into migrateHarbor
so stopping harbor.service is issued again right before backing up
operation.
Fixes #2360

Fix backup Harbor database error

---

installer/build/ova-manifest.json
installer/build/scripts/upgrade/notary-migration-fix.sh
installer/build/scripts/upgrade/upgrade-harbor.sh

Fix notary upgrade failure caused by migrating mysql to pqsl.
Fixes #

Fix notary upgrade failure from harbor 1.4

---

docs/user_doc/vic_vsphere_admin/backup_vic_appliance.md

Fixes https://github.com/vmware/vic-product/issues/2110.
@renmaosheng can you please assign a reviewer? @hickeng, @zjs and @dbarkelew can you also please take a look?
The section on restoring by using the `ovfEnv` file requires a procedure. I could not find any information online about how to do this. @dbarkelew suggests using MOB, `govc`, or PowerCLI, but I couldn't find anything about using these tools to import an OVF env file.

Updated the appliance backup procedures

---

.drone.yml

Pack Admiral vic_v1.5.2 for VIC 1.5.2 release.
Fixes #

Pack Admiral 1.5.2

---

installer/build/scripts/upgrade/upgrade-harbor.sh

notary-migration-fix.sh is required for all VIC versions upgrading.
Fixes #

Execute notary-migration-fix.sh for all versions

---

installer/build/scripts/upgrade/upgrade-harbor.sh

Notary patch is not executed on 1.5 and above upgrade. Move it before
service start to ensure it runs on all versions upgrade.
Fixes #

Fix habor 1.5 and above notary upgrade

---

installer/build/scripts/upgrade/upgrade.sh

If reconfigure_token is enable, it restarts admiral and harbor
services whenever it detects psc-config.properties changed. During
upgrade the new appliance will register itself to PSC and regenerate
psc-config.properties so admiral and harbor are restarted even they
are disabled.
Fixes #

Disable reconfigure_token during upgrade

---

installer/build/scripts/systemd/scripts/vic-appliance-tls.sh
tests/manual-test-cases/Group2-OVA-Features/2-05-Customized-Configurations.robot

The custom certificates loaded in vApp through HTML5, has the space in
every 64 chars. Those spaces need to be removed before adding '\n' for
every 64 chars in generating certs
Fix #2173

Remove the space in the custom certificates

---

docs/user_doc/vic_vsphere_admin/backup_vic_appliance.md
docs/user_doc/vic_vsphere_admin/interop.md
docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md

This ports the fix from https://github.com/vmware/vic-product/pull/2361 (for the 1.5 docs) into the 1.4.x docs.
@jitinkumar2018 can you please confirm that the same procedure for 1.5.x also applies in 1.4.x? Thanks!

Updated appliance backup procedures for 1.4.x

---

installer/fileserver/routes/index.go

To be consisent to OVA installer.
Fixes #2443

Increase vic password length in init page

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/vch_admin_client.md
docs/user_doc/vic_vsphere_admin/vch_portlet_ui.md

Hi @stuclem ,
I added a note to say that VIC 1.5.2 and later versions don't include the Flex client.
Do I have to add the note in all topics that mention the Flex client?
Fixes #2429 
Thanks,
Vidya

Note - VIC 1.5.2 & later don't support Flex client

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Updated https://vmware.github.io/vic-product/assets/files/html/latest/vic_vsphere_admin/deploy_vic_appliance.html to say that VIC 1.5.3 and later versions have a limit of 128 characters.
Fixes #2447 
@stuclem , can you please review this?
Thanks,
Vidya

Updated password length

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Hi @stuclem ,
Modified https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/upgrade_appliance.html to include support for appliance FQDN.
Fixes #2422 
Thanks,
Vidya

Added that ugrade script now supports appliance FQDN

---

installer/build/scripts/admiral/configure_admiral.sh

custom.config is for user 's customized configurations and should
not be overwritten. Use it as the base context of config.properties
and append auto generated configurations.
localhost, 127.0.0.1, ui, ${HOSTNAME} is important for the internal
connections on the VIC Appliance between the Admiral service and
the Harbor registry. Include them in no proxy list whenever proxy
is configured.
When proxy is not set or removed in the vApp Options, set them as
null clearly.
Fixes #

Add internal no proxy and keep custom.config

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Reverts vmware/vic-product#2464
Apparently the FQDN support was not implemented. See https://github.com/vmware/vic-product/issues/1731#issuecomment-496405619.

Revert "Added that ugrade script now supports appliance FQDN"

---

installer/build/build-cache.sh

registry:2.6.2-photon is deprecated after harbor is embeded.
Fixes #

Remove unused docker image

---

installer/fileserver/files/open_source_license.txt

Updating OSL to including the latest package update to fix the CVE-2019-11477.

Updating OSL to including info of fixing the CVE-2019-1147

---

installer/build/build-cache.sh

In air-gaped environment Harbor fails to start because it can not
pull vmware/registry:2.6.2-photon on internet. Use registry image
from Harbor bundle instead.
Fixes #

Use registry image from Harbor bundle

---

docs/user_doc/vic_vsphere_admin/vch_cert_reqs.md

Fixes https://github.com/vmware/vic-product/issues/2460
@wjun, does this cover everything from internal bug 2339700? Thanks!

Corrections in certificates docs

---

tests/resources/nimbus-testbeds/vic-multi-cls.rb

Rename shared datastore in the vic-multi-cls ruby file

---

installer/build/ova-manifest.json
installer/build/scripts/appliance/appliance-logrotate

Cron generate tons of logs so rotate log files whenever it reach
200M.
Fixes #

Rotate log files of cron

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-05-Enhanced-Linked-Mode.robot

Some test cases are not supported in the vsphere7.0,
so skipping the test cases using tag.

Set a tag for skipping test cases used the tag

---

dinv/dch-photon-18.06/Dockerfile

For go 1.8, go get dependencies pkg failed, so
update go version to 1.11 for resolving the issue.

Update go version for building dch image

---

installer/build/bootable/repo/photon-local.repo
installer/build/bootable/repo/photon-updates-local.repo

after the remote photon repo was migrated, we do not see some latest rpm package
on the browser, so we do not download these rpm package to local photon repo,
so we have to replace local repo to remote repo.

Replace local photon repo to remote photon repo

---

.drone.yml

This logs can only be accessed by internal users,
other users cannot access,
so we need to make it private.

Changed GCP acl for testing logs
