index.html

[skip ci] Fixed link to beta docs.

---

index.html

[skip ci] Added link to official product page and fixed trademarking.

---

assets/files/html/0.8/vic_installation/download_vic.html
index.html

[skip ci]  Also fixed broken link.

[skip ci] Added support and license for GA product

---

assets/files/html/0.8/vic_app_dev/using_vic_with_harbor.html

[skip ci] Fixed broken link in docs

---

README.md

Fixed the same spacing issue

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_dev_ops/add_repos_in_portal.md
docs/user_doc/vic_dev_ops/add_vchs_in_portal.md
docs/user_doc/vic_dev_ops/manage_containers_portal.md
docs/user_doc/vic_dev_ops/provision_containers_portal.md
docs/user_doc/vic_dev_ops/using_management_portal.md

Adding skeleton topics so that we can get an idea of what the finished DevOps doc will look like.

Adding skeleton topics for Management Portal usage

---

docs/user_doc/vic_dev_ops/add_repos_in_portal.md
docs/user_doc/vic_dev_ops/add_vchs_in_portal.md
docs/user_doc/vic_dev_ops/manage_containers_portal.md
docs/user_doc/vic_dev_ops/provision_containers_portal.md

Added some sections to the skeleton docs.

---

index.html

Removed PDF links for Harbor.

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/restart_services.md
docs/user_doc/vic_vsphere_admin/service_status.md

Fixes https://github.com/vmware/vic-product/issues/135.
Very short topics on restarting the different services. It would be great if we could add some information about what might cause the services to fail or die, and how to remedy that. @frapposelli, any ideas?
Thanks!

Added info about status/restart for the OVA services

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_dev_ops/add_repos_in_portal.md
docs/user_doc/vic_dev_ops/add_vch_fullTLS_in_portal.md
docs/user_doc/vic_dev_ops/add_vch_noTLS_in_portal.md
docs/user_doc/vic_dev_ops/add_vch_serversideTLS_in_portal.md
docs/user_doc/vic_dev_ops/add_vchs_in_portal.md
docs/user_doc/vic_dev_ops/create_network.md
docs/user_doc/vic_dev_ops/creating_placements.md
docs/user_doc/vic_dev_ops/provision_containers_portal.md
docs/user_doc/vic_dev_ops/vchs_and_mgmt_portal.md

Fixes #62 
Fixes #119 
Content:
- Add Hosts with No TLS Authentication to the Management Portal
- Add Hosts with Server-Side TLS Authentication to the Management Portal
- Add Hosts with Full TLS Authentication to the Management Portal
- Create and Manage Container Placements
- Create New Networks for Provisioning Containers
- Add Registries to the Management Portal

Adding user doc for Admiral

---

docs/user_doc/vic_vsphere_admin/upgrade_vch.md
docs/user_doc/vic_vsphere_admin/upgrade_vch_options.md

Per title. Fixes https://github.com/vmware/vic-product/issues/46.
@gigawhitlocks can you please take a look? Thanks!

Added --rollback option.

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/deploy_vch_esxi.md
docs/user_doc/vic_vsphere_admin/deploy_vch_vcenter.md
docs/user_doc/vic_vsphere_admin/open_ports_on_hosts.md
docs/user_doc/vic_vsphere_admin/remove_vch.md
docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md
docs/user_doc/vic_vsphere_admin/ts_firewall_error.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md
docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md
docs/user_doc/vic_vsphere_admin/vicadmin_status_ref.md

Per title. 
Fixes https://github.com/vmware/vic-product/issues/45.
@andrewtchin can you please take a look? Thanks!

Added firewall update command

---

docs/user_doc/vic_vsphere_admin/interop.md

- Fixes https://github.com/vmware/vic-product/issues/41
- Fixes https://github.com/vmware/vic-product/issues/89
- Fixes https://github.com/vmware/vic-product/issues/84
- Fixes https://github.com/vmware/vic-product/issues/87

Updated interop statements for 1.1

---

docs/user_doc/vic_app_dev/README.md
docs/user_doc/vic_app_dev/build_app_with_vic.md
docs/user_doc/vic_app_dev/container_limitations.md
docs/user_doc/vic_app_dev/container_operations.md

Also clarified that the docker compose example is an excerpt, rather than the full example.
- Fixes https://github.com/vmware/vic-product/issues/140
- Fixes https://github.com/vmware/vic-product/issues/139

Added versions in which Docker command support was added

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/upgrading_vic.md

Per title. Fixes https://github.com/vmware/vic-product/issues/124.
@anchal-agrawal @mhagen-vmware @frapposelli can you please confirm that these are the only prereqs? Thanks!

Added system requirements for OVA

---

docs/user_doc/vic_vsphere_admin/vch_installer_examples.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

- Fixes https://github.com/vmware/vic-product/issues/43
- Fixes https://github.com/vmware/vic-product/issues/53
- Fixes https://github.com/vmware/vic-product/issues/54
@dougm can you please check #43? Thanks!
#53 and #54 are too trivial to bother anyone about.

Minor changes in vic-machine create options descriptions

---

docs/user_doc/vic_app_dev/configure_docker_client.md
docs/user_doc/vic_dev_ops/using_registry.md

Towards https://github.com/vmware/vic-product/issues/153.
@reasonerjt and @hainingzhang can you please take a look? 
This is purely a token effort to make sure that Notary is at least mentioned in the GA docs. I can and will make further updates post-GA, if necessary (which I am sure it is). 
For instance, we definitely need the commands to configure Windows and Mac Docker clients.
Thanks!

Added minimal info about Notary.

---

docs/user_doc/vic_vsphere_admin/cmdline_login.md
docs/user_doc/vic_vsphere_admin/vch_installer_examples.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Towards https://github.com/vmware/vic-product/issues/44
@andrewtchin and @hickeng can you please take a look?

Added example of combining custom and autogen certs

---

docs/user_doc/vic_vsphere_admin/debug_vch.md
docs/user_doc/vic_vsphere_admin/debug_vch_options.md
docs/user_doc/vic_vsphere_admin/log_bundles.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md
docs/user_doc/vic_vsphere_admin/vch_shell_access.md
docs/user_doc/vic_vsphere_admin/vch_ssh_access.md

- Towards https://github.com/vmware/vic-product/issues/68 (`vic-machine create debug` levels)
- Towards https://github.com/vmware/vic-product/issues/151 (`vic-machine debug` password expiry)
- Towards https://github.com/vmware/vic-product/issues/55 (log rotation)
- Towards https://github.com/vmware/vic-product/issues/52 (added links in log bundle topic)
@hickeng can you please take a look at the two debug issues?
@fdawg4l can you please look at the logging issues? 
Thanks!

Updates related to debug and logging

---

docs/user_doc/README.md
docs/user_doc/vic_app_dev/README.md
docs/user_doc/vic_app_dev/overview_of_vic_appdev.md
docs/user_doc/vic_dev_ops/README.md
docs/user_doc/vic_dev_ops/overview_of_vic_devops.md
docs/user_doc/vic_vsphere_admin/README.md
docs/user_doc/vic_vsphere_admin/introduction.md

Per title. Towards https://github.com/vmware/vic-product/issues/38.

Making the overviews a bit less engine-centric.

---

docs/user_doc/vic_vsphere_admin/security_reference.md

Fixed link syntax per comment from @andrewtchin.

---

docs/user_doc/vic_vsphere_admin/set_up_ops_user.md

Fixes https://github.com/vmware/vic-product/issues/191.
@hickeng can you please review?

Added three missing roles to ops-user topic.

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_registry.md

Reviewed by @frapposelli via Slack

Added that one should back up before upgrade

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Fixes https://github.com/vmware/vic-product/issues/202.
@frapposelli is this OK? Thanks!

Added that DNS servers for OVA use space separation.

---

docs/user_doc/README.md
docs/user_doc/vic_app_dev/README.md
docs/user_doc/vic_dev_ops/README.md
docs/user_doc/vic_vsphere_admin/README.md

Added that doc applies to all 1.1.x releases.

---

docs/user_doc/vic_dev_ops/add_repos_in_portal.md
docs/user_doc/vic_dev_ops/vchs_and_mgmt_portal.md

Fixes #186 harbor instances mentions

---

docs/user_doc/vic_vsphere_admin/debug_vch_options.md

Fixes https://github.com/vmware/vic-product/issues/151, following comment from @hickeng in PR https://github.com/vmware/vic-product/pull/158. 
@hickeng is this OK now?

Correction in password expiry doc

---

docs/user_doc/vic_vsphere_admin/cmdline_login.md
docs/user_doc/vic_vsphere_admin/vch_installer_examples.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Following @hickeng 's comments in https://github.com/vmware/vic-product/pull/162#pullrequestreview-33089799, which fixes https://github.com/vmware/vic-product/issues/44.

Comments from George about cert combos.

---

docs/user_doc/vic_dev_ops/creating_users_registry.md

Fixes https://github.com/vmware/vic-product/issues/204. 
@reasonerjt is this OK now? Thanks!

Added that passwords can include special characters.

---

docs/user_doc/SUMMARY.md

Also changed the presentation a little.

Adjusting product version number to TOC

---

.drone.yml
dinv/build.sh
dinv/ci.sh
dinv/dinv-1.13/Dockerfile
dinv/dinv-1.13/Dockerfile.official-image
dinv/dinv-1.13/certgen/main.go
dinv/dinv-1.13/dinv

Add DINV work to repo

---

index.html

Fixes https://github.com/vmware/vic-product/issues/74

Changed download link from bintray to google.

---

docs/user_doc/vic_app_dev/container_operations.md
docs/user_doc/vic_app_dev/network_use_cases.md
docs/user_doc/vic_vsphere_admin/vch_installer_examples.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/212.
Also cleaned up the network use-cases topic a bit too.
@hmahmood is this OK? Thanks!

Added how to set static IP on a container VM

---

docs/user_doc/README.md

Fixed link to TM page

---

docs/user_doc/vic_dev_ops/add_repos_in_portal.md
docs/user_doc/vic_vsphere_admin/vch_installer_examples.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/171. @jzt, is this better? Thanks!

Clarified insecure-registry option.

---

docs/user_doc/vic_vsphere_admin/vch_installer_examples.md

Reverts vmware/vic-product#232

Revert "Small correction from Zach"

---

docs/user_doc/vic_app_dev/container_operations.md
docs/user_doc/vic_app_dev/using_volumes_with_vic.md

Fixes https://github.com/vmware/vic-product/issues/181. @matthewavery do we need add more? Thanks!

Added that VIC only supports EXT4 volumes.

---

docs/user_doc/vic_vsphere_admin/interop.md
docs/user_doc/vic_vsphere_admin/networks.md

Fixes https://github.com/vmware/vic-product/issues/73. 
@dougm, @mhagen-vmware is this OK? Do we need to add any caveats for NSX support in 1.1.x? Thanks!

Added NSX support statement.

---

docs/setup/beta/README.md

Corrected the markdown syntax to allow nice rendering. :-)

fixed markdown syntax

---

docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md

Included workaround for #5204.

---

docs/user_doc/README.md
docs/user_doc/vic_app_dev/README.md
docs/user_doc/vic_dev_ops/README.md
docs/user_doc/vic_vsphere_admin/README.md

Included both 2016 and 2017 in copyright range, per guidelines.

Fixed copyright range to include 2016.

---

docs/user_doc/README.md
docs/user_doc/vic_dev_ops/add_repos_in_portal.md
docs/user_doc/vic_dev_ops/using_registry.md
docs/user_doc/vic_vsphere_admin/deploy_vch.md
docs/user_doc/vic_vsphere_admin/download_vic.md
docs/user_doc/vic_vsphere_admin/set_up_ops_user.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md
docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md

Fixes https://github.com/vmware/vic-product/issues/260.

Fixed some broken links

---

installer/engine_installer/engine_installer.go

Fix engine-installer broken compile

---

installer/ovatools/vic-ova-ui/main.go

Add fileserver and installer links to ova

---

docs/user_doc/vic_vsphere_admin/contents_of_vic_binaries.md
docs/user_doc/vic_vsphere_admin/deploy_vch.md
docs/user_doc/vic_vsphere_admin/deploy_vch_esxi.md
docs/user_doc/vic_vsphere_admin/deploy_vch_vcenter.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/download_vic.md
docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md

Fixes https://github.com/vmware/vic-product/issues/311.
@andrewtchin can you please take a look? Thanks!

Clarified where to download vic engine, and not to download UI files.

---

docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/247. 
@morris-jason can you please take a look?

Added warning about spaces in container network port group names.

---

installer/packer/scripts/kov/configure_kov.sh
installer/packer/scripts/systemd/kov/kov_env_vars.service

Fix issues

---

docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/325.
@matthewavery can you please take a look?

Added that the volume store label must be unique.

---

installer/packer/packer-vic.json
installer/packer/scripts/kov/configure_kov.sh
installer/packer/scripts/kov/configure_kov_env_vars.sh
installer/packer/scripts/kov/configure_kov_published_env_vars.sh
installer/packer/scripts/provision_kov.sh
installer/packer/scripts/system_settings.sh
installer/packer/scripts/systemd/data.mount
installer/packer/scripts/systemd/fileserver/fileserver.service
installer/packer/scripts/systemd/kov/kov.service
installer/packer/scripts/systemd/kov/kov_env_vars.service
installer/packer/scripts/systemd/kov/kov_published_env_vars.service
installer/packer/scripts/systemd/repartition.service
installer/packer/scripts/systemd/resize_data_volume.sh

ova deployment verified
fixes: https://github.com/vmware/kov/issues/244
fixes: https://github.com/vmware/kov/issues/226
fixes: https://github.com/vmware/kov/issues/285

Add one file including all kov concerning env vars to kov bundle

---

installer/packer/scripts/kov/configure_kov.sh
installer/packer/scripts/kov/configure_kov_published_env_vars.sh

fixes: https://github.com/vmware/kov/issues/278
```
➜  installer git:(seperate_bundle) ✗ curl -k https://10.160.83.106:9443
<pre>
<a href="com.vmware.vic-v1.1.1-rc1.zip">com.vmware.vic-v1.1.1-rc1.zip</a>
<a href="com.vmware.vic.ui-v1.1.1-rc1.zip">com.vmware.vic.ui-v1.1.1-rc1.zip</a>
<a href="kov-darwin-amd64-dev.tar.gz">kov-darwin-amd64-dev.tar.gz</a>
<a href="kov-linux-amd64-dev.tar.gz">kov-linux-amd64-dev.tar.gz</a>
<a href="kov-linux-arm-dev.tar.gz">kov-linux-arm-dev.tar.gz</a>
<a href="kov-windows-amd64-dev.tar.gz">kov-windows-amd64-dev.tar.gz</a>
<a href="vic_1.1.1-rc1.tar.gz">vic_1.1.1-rc1.tar.gz</a>
</pre>
```
```
root@localhost [ /opt/vmware/fileserver/files ]# tar tvf kov-linux-amd64-dev.tar.gz
-rwx------ root/root   8638656 2017-06-29 04:51 bin/kov
drwx------ root/root         0 …
```

Put kov binary in seperate bundles for different platform

---

installer/packer/scripts/admiral/configure_admiral.sh
installer/packer/scripts/kov/configure_kov.sh
installer/packer/scripts/systemd/admiral/admiral_startup.service
installer/packer/scripts/systemd/engine_installer/engine_installer_startup.service
installer/packer/scripts/systemd/fileserver/fileserver_startup.service
installer/packer/scripts/systemd/harbor/harbor_startup.service
installer/packer/scripts/systemd/kov/kov.service
installer/scripts/build.sh

Update systemd units with iptables deps

---

installer/README.md
installer/packer/packer-vic.json
installer/packer/scripts/admiral/configure_admiral.sh
installer/packer/scripts/admiral/start_admiral.sh
installer/packer/scripts/harbor/configure_harbor.sh
installer/packer/scripts/harbor/start_harbor.sh
installer/packer/scripts/package_provisioning.sh
installer/packer/scripts/system_settings.sh
installer/packer/scripts/systemd/admiral/admiral_startup.path
installer/packer/scripts/systemd/admiral/admiral_startup.service
installer/packer/scripts/systemd/engine_installer/engine_installer.service
installer/packer/scripts/systemd/fileserver/fileserver.service
installer/packer/scripts/systemd/fileserver/fileserver_startup.service
installer/packer/scripts/systemd/harbor/harbor.service
installer/packer/scripts/systemd/harbor/harbor_startup.path
installer/packer/scripts/systemd/harbor/harbor_startup.service
installer/packer/scripts/systemd/kov/kov_published_env_vars.service

Start Admiral and Harbor after token file appears at `/etc/vmware/psc/admiral/token` and `/etc/vmware/psc/harbor/token`

Add systemd path units for SSO integration

---

installer/packer/scripts/engine_installer/configure_engine_installer.sh
installer/packer/scripts/fileserver/configure_fileserver.sh
installer/packer/scripts/kov/configure_kov.sh
installer/packer/scripts/provision_fileserver.sh
installer/packer/scripts/systemd/engine_installer/engine_installer_startup.service
installer/packer/scripts/systemd/fileserver/fileserver_startup.service
installer/packer/vic-unified.ovf

fixes: https://github.com/vmware/kov/issues/311
fixes: https://github.com/vmware/vic-product/issues/413
manual deployment:

Fix start kov

---

installer/packer/scripts/kov/configure_kov.sh
installer/packer/scripts/provision_fileserver.sh
installer/packer/scripts/provision_kov.sh

fixes: https://github.com/vmware/kov/issues/327
```
root@localhost [ ~ ]# systemctl restart kov
root@localhost [ ~ ]# systemctl restart kov
root@localhost [ ~ ]# cd /opt/vmware/fileserver/files/
root@localhost [ /opt/vmware/fileserver/files ]# for i in `ls vic-adm-*`; do echo $i; tar tvf $i; done
vic-adm-darwin-amd64-dev.tar.gz
-rwx------ root/root  22520144 2017-07-12 16:54 bin/vic-adm
drwx------ root/root         0 2017-07-12 16:54 certs/
-rw------- root/root      1972 2017-07-12 16:54 certs/admin.crt
-rw------- root/root      2134 2017-07-12 16:54 certs/ca.crt
-rw------- root/root      3268 2017-07-12 16:54 certs/admin.key
-rw-r--r-- root/root       786 2017-07-12 16:54 env.sh
-rw------- root/root  72380288 2017-07-12 16:54 kubectl
vic-adm-linux-amd64-dev.tar.gz
-rwx------ root/root …
```

persist kubectl and add it to bundle

---

docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_windows.md

Fixes #378.
Josh, can you have a look whether these changes are okay, according to the changed scripts.

Fixed pligins procedures for 1.2

---

installer/README.md
installer/fileserver/tasks.go
installer/packer/packer-vic.json
installer/packer/scripts/psc/get_token.sh
installer/packer/scripts/psc/put_token_guestinfo.sh
installer/packer/scripts/system_settings.sh
installer/packer/scripts/systemd/admiral/admiral_startup.service
installer/packer/scripts/systemd/harbor/harbor_startup.path
installer/packer/scripts/systemd/psc/get_token.service

Create PSC tokens during OVA init

---

installer/packer/packer-vic.json
installer/packer/scripts/system_settings.sh
installer/packer/scripts/systemd/psc/get_token.service
installer/packer/scripts/systemd/psc/get_token.timer

Add systemd timer to refresh PSC tokens

---

installer/packer/scripts/harbor/configure_harbor.sh
installer/packer/scripts/harbor/start_harbor.sh
installer/packer/vic-unified.ovf

- Remove password options from OVA deploy wizard
- Set random `db_password` and `clair_db_password` on first boot
Fixes https://github.com/vmware/vic/issues/4727

Update Harbor OVA/SSO config, generate passwords

---

installer/packer/scripts/admiral/configure_admiral.sh

Fixes https://github.com/vmware/vic/issues/5181

Use Java keytool alias

---

installer/packer/scripts/psc/get_token.sh
installer/packer/scripts/systemd/harbor/harbor_startup.path

This reverts commit e6d152ca35cb4c4065010df011ca8bc7836f4bf8.

Revert "PSC: copy Harbor token file to volume mount (#476)"

---

installer/ovatools/vic-ova-ui/main.go

Add init message to OVA console

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_quickstart.md
docs/user_doc/vic_vsphere_admin/deploy_kubernetes_cluster.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Per decision to drop KOV from VIC.

Removing KOV from the docs.

---

installer/packer/scripts/admiral/start_admiral.sh

This change adds a `CONFIG_FILE_PATH` env variable needed by Admiral.
Fixes #518

Update Admiral's docker run command

---

installer/fileserver/tasks.go
installer/ovatools/vic-ova-ui/main.go

Static analysis: use abs path for binaries

---

installer/packer/scripts/admiral/start_admiral.sh

Add Admiral data volume

---

installer/ovatools/vic-ova-ui/main.go
installer/packer/packer-vic.json
installer/packer/scripts/admiral/configure_admiral.sh
installer/packer/scripts/harbor/configure_harbor.sh
installer/packer/scripts/harbor/start_harbor.sh
installer/packer/scripts/harbor/upgrade_from_0.5.sh
installer/packer/scripts/package_provisioning.sh
installer/packer/scripts/provision_harbor.sh
installer/packer/scripts/upgrade/upgrade_1.1_to_1.2.sh
installer/packer/vic-unified.ovf

Towards https://github.com/vmware/vic/issues/4726

Harbor upgrade and data migration script

---

docs/user_doc/vic_app_dev/add_users_registry.md
docs/user_doc/vic_app_dev/create_network.md
docs/user_doc/vic_app_dev/manage_project_members.md
docs/user_doc/vic_app_dev/provision_containers_portal.md
docs/user_doc/vic_cloud_admin/access_project_logs.md
docs/user_doc/vic_cloud_admin/assign_admin_role.md
docs/user_doc/vic_cloud_admin/configure_registry.md
docs/user_doc/vic_cloud_admin/create_replication_endpoints.md
docs/user_doc/vic_cloud_admin/create_replication_rules.md
docs/user_doc/vic_cloud_admin/creating_projects_registry.md
docs/user_doc/vic_cloud_admin/creating_users_registry.md
docs/user_doc/vic_cloud_admin/manage_projects.md
docs/user_doc/vic_cloud_admin/manage_replication_endpoints.md
docs/user_doc/vic_cloud_admin/manage_repository_registry.md
docs/user_doc/vic_vsphere_admin/deploy_vch_registry.md

Where possible, I have done global search and replace for recurring texts that related to now defunct VIC Registry UI options.
Towards https://github.com/vmware/vic-product/issues/328. This is by no means complete.

WIP Updates for unified UI

---

installer/packer/scripts/harbor/configure_harbor.sh

Update hostname in Harbor config

---

installer/Makefile
installer/engine_installer/logstream.go
installer/engine_installer/server.go
installer/fileserver/html/index.html
installer/fileserver/server.go
installer/lib/login.go
installer/ovatools/vic-ova-ui/main.go
installer/packer/packer-vic.json

Fixes: vmware/vic#5458
Fixes: vmware/vic-product#517
Fixes: vmware/vic-product#493

OVA Webservers UI Enhancements

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Documented how to obtain OVA IP address.

---

installer/ovatools/vic-ova-ui/main.go
installer/ovatools/vic-ova-ui/network_status.go
installer/packer/scripts/systemd/network/network-config.sh

Fixes #549 
Tested with combinations of Static Address, Gateway, Netmask, and DNS.

Conditional Network Config on Static Addresses

---

docs/user_doc/vic_vsphere_admin/contents_of_vic_binaries.md
docs/user_doc/vic_vsphere_admin/deploy_demo_vch.md
docs/user_doc/vic_vsphere_admin/deploy_vch.md
docs/user_doc/vic_vsphere_admin/deploy_vch_esxi.md
docs/user_doc/vic_vsphere_admin/deploy_vch_registry.md
docs/user_doc/vic_vsphere_admin/deploy_vch_vcenter.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/open_ports_on_hosts.md
docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_windows.md

Fixes https://github.com/vmware/vic-product/issues/572.
@morris-jason can you please review?

Removed https and 9443 from appliance address

---

installer/fileserver/html/index.html
installer/fileserver/server.go

OVA Tag UX Improvments

---

installer/ovatools/vic-ova-ui/main.go
installer/ovatools/vic-ova-ui/network_status.go

Fixes a bug where the loopback address and docker gateways were included in the network status panel.

Fix localhost inclusion in network status panel

---

installer/packer/scripts/provision_admiral.sh
installer/packer/scripts/provision_harbor.sh
installer/packer/scripts/system_settings.sh
installer/packer/scripts/upgrade/upgrade_1.1_to_1.2.sh

Adds OVA upgrade script - includes Admiral and Harbor upgrade components
Fixes https://github.com/vmware/vic/issues/4726 and https://github.com/vmware/vic/issues/5588

OVA Upgrade

---

installer/fileserver/server.go

Add JS http route to fileserver

---

installer/packer/scripts/admiral/configure_admiral.sh
installer/packer/scripts/harbor/configure_harbor.sh
installer/packer/vic-unified.ovf

Use Admiral cert for Harbor

---

docs/user_doc/vic_vsphere_admin/inspect_vch_config.md

Fixes https://github.com/vmware/vic-product/issues/557.
@emlin is this OK? Thanks!

Updated inspect config to reflect new behaviour.

---

installer/packer/scripts/systemd/docker.service

Update docker unit file

---

docs/user_doc/vic_vsphere_admin/deploy_demo_vch.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
installer/fileserver/html/index.html
installer/packer/scripts/systemd/engine_installer/engine_installer.service
installer/packer/scripts/systemd/engine_installer/engine_installer_startup.service
installer/packer/vic-unified.ovf

use Demo VCH Installer Wizard name everywhere

---

docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md

Minor formatting error causing inappropriate numbering/bullets.

Fixed missing line break

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/common_vic_options.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md
docs/user_doc/vic_vsphere_admin/vic_env_variables.md

Fixes https://github.com/vmware/vic-product/issues/319.
@morris-jason can you please review? Thanks!

Added doc about vic-machine environment variables.

---

docs/user_doc/vic_vsphere_admin/access_h5_ui.md
docs/user_doc/vic_vsphere_admin/vch_portlet_ui.md
docs/user_doc/vic_vsphere_admin/verify_vch_deployment.md

Fixes https://github.com/vmware/vic-product/issues/198.
@dougm can you please review?

Mentioned that you cannot delete container VMs in client.

---

docs/user_doc/vic_app_dev/configure_docker_client.md
docs/user_doc/vic_app_dev/container_operations.md

Fixes https://github.com/vmware/vic-product/issues/560.
@mdubya66 can you please review?

Updated Docker client version.

---

installer/fileserver/html/css/style.css
installer/fileserver/html/index.html

Fixes #555 
Fixes #567 
Fixes #591

Fix getting started layout issues

---

docs/user_doc/vic_overview/introduction.md

Updating the overview so that it reflects the 1.2 authentication, users, and roles.

Updated the authentication and user roles info

---

installer/fileserver/html/index.html

Update documentation links

---

installer/ovatools/vic-ova-ui/main.go

Fix vic-ova-ui text alignment

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_cloud_admin/logging_in_MP.md
docs/user_doc/vic_overview/introduction.md

Part of clarifying the users story in 1.2.
Added a concept topic in the MP doc, added to Summary.

Added info on log in to MP for 1st time

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Fixes https://github.com/vmware/vic-product/issues/633.

Added NTP as prereq for appliance install.

---

installer/fileserver/html/index.html

Fix re-initialize button in Getting Started page

---

installer/packer/scripts/admiral/configure_admiral.sh

From PR https://github.com/vmware/vic-product/pull/642
Cherry picks b65f509a0af126d7e53caa39c74e8d00aa0d4164

Chain self signed Admiral server cert with root

---

installer/packer/scripts/provision_fileserver.sh

Update fileserver provisioning for UI plugin files

---

docs/user_doc/vic_app_dev/configure_docker_client.md
docs/user_doc/vic_cloud_admin/add_repos_in_portal.md
docs/user_doc/vic_vsphere_admin/vch_installer_examples.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/646.
@gigawhitlocks, @emlin and @reasonerjt can you please confirm that this is correct and review?

Clarified that you cannot use --insecure-registry with VIC Registry.

---

installer/packer/vic-unified.ovf

Fix typos in OVF descriptor, issue: #651. Addendum.

Change Info for Example Users

---

docs/user_doc/vic_cloud_admin/vchs_and_mgmt_portal.md
docs/user_doc/vic_overview/introduction.md
docs/user_doc/vic_vsphere_admin/verify_vch_deployment.md

Feedback sent by email. Minor fixes. @alextopuzov can you please review?

Fixes from Eduardo.

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Fixes https://github.com/vmware/vic-product/issues/383
@morris-jason is this enough?

Documenting network status console for appliance VM

---

installer/packer/vic-unified.ovf

Fix OVF params for Example Users.
Cherry picks bfaec25, 4eefc54
From PR #582 #673

Implement support for creating default users in the OVA

---

installer/packer/scripts/admiral/configure_admiral.sh
installer/packer/scripts/fileserver/configure_fileserver.sh

Increase self signed cert expiration

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Towards https://github.com/vmware/vic-product/issues/289.
This PR covers the steps in the OVA deployment in which you configure the OOTB users. @alextopuzov is covering the description and use of these users elsewhere.
@lcastellano can you please review this PR? Thanks!

Added OVA step for OOTB user creation.

---

docs/user_doc/vic_app_dev/network_use_cases.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/575.
@hmahmood can you please review? Thanks!

Documented that default container network trust level is publish

---

installer/packer/scripts/system_settings.sh
installer/packer/scripts/systemd/appliance/chrootpwd.sh

Removes password expiration for root user during build, restores it after firstboot of the deployed VM

Fix password expiration in OVA

---

docs/user_doc/vic_vsphere_admin/networks.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md

Comments from Eduardo's review

---

installer/packer/scripts/system_settings.sh
installer/packer/scripts/systemd/appliance/chrootpwd.sh

Cherry picks ed1241d45e57f6f7e9bf1103b02acf8ad3d3d77f
From PR #691

Fix password expiration in OVA 

---

docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md

Fixes https://github.com/vmware/vic-product/issues/613.
@jooskim is this OK?

Added awk as a prereq for plugin and merged ui commands

---

docs/user_doc/vic_quickstart.md

Updated the quickstart links.
@karthik-narayan are these the correct topics that you want to see called out in this page? I didn't want to overpopulate it. 
You can see the file here: https://github.com/stuclem/vic-product/blob/quick/docs/user_doc/vic_quickstart.md

Updated quickstart links

---

installer/packer/scripts/provision_harbor.sh
installer/packer/scripts/system_settings.sh

Fixes https://github.com/vmware/vic/issues/5463

Add DCH to OVA

---

installer/packer/scripts/provision_harbor.sh

Update DCH image tag

---

LICENSE
NOTICE
installer/fileserver/files/open_source_license.txt
installer/packer/packer-vic.json

Cherry picks 86a463f3f2ecd832f139f0a3569b7e6f94882bba
From PR #721

Update LICENSE and NOTICE

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md
docs/user_doc/vic_vsphere_admin/ts_plugin_script_fails.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_windows.md

Fixes https://github.com/vmware/vic-product/issues/704
@jooskim can you please review? Thanks!

Added warning about thumbprint variable to plug-in topics

---

docs/user_doc/vic_cloud_admin/add_repos_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_fullTLS_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_noTLS_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_serversideTLS_in_portal.md
docs/user_doc/vic_cloud_admin/configure_system.md
docs/user_doc/vic_cloud_admin/create_projects.md

- Fixes https://github.com/vmware/vic-product/issues/333
- Fixes https://github.com/vmware/vic-product/issues/645
- Fixes https://github.com/vmware/vic-product/issues/338

Working on MP procedures

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md
docs/user_doc/vic_vsphere_admin/ts_no_access_to_vic_services.md

Fixes https://github.com/vmware/vic-product/issues/666. 
@andrewtchin does this cover it? Thanks!

Added troubleshooting topic on accessing VIC services from 172 networks

---

installer/packer/scripts/upgrade/upgrade_1.1_to_1.2.sh

From https://github.com/vmware/admiral/issues/191

Fix Admiral upgrade

---

docs/user_doc/vic_vsphere_admin/restart_services.md
docs/user_doc/vic_vsphere_admin/service_status.md

No associated issue, but I noticed in https://github.com/vmware/admiral/issues/191 that that the systemctl commands used by @lazarin are different to what I have documented.
@andrewtchin is this now correct? Should there be another command for the Demo VCH service?

Updating systemctl commands

---

docs/user_doc/vic_vsphere_admin/pre_upgrade_tasks.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_data.md

Fixes https://github.com/vmware/vic-product/issues/733 and removes the arguments from running the script.
@andrewtchin can you please review? Thanks!

More upgrade doc updates

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md
docs/user_doc/vic_vsphere_admin/ts_appliance_password_refused.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Fixes https://github.com/vmware/vic-product/issues/668

Added troubleshooting topic on appliance password refusal

---

docs/user_doc/vic_vsphere_admin/networks.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/210. Or, more accurately, attempts to.
Really not very sure about this, because networking really is a weak spot for me.

Attempting to document --asymmetric-routes

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Fixes https://github.com/vmware/vic-product/issues/745.
Still need to address the question of whether you can have more than one appliance per PSC, asked in https://github.com/vmware/vic-product/issues/740.
@andrewtchin and @mdubya66 can you please review?

Stated that you can only run one appliance per VC.

---

installer/packer/scripts/upgrade/upgrade_1.1_to_1.2.sh

Cherry picks commit 7ac1f3807f22aeaec947cb24be4d6aef504336a6
From PR #756

Fix Harbor upgrade issue

---

installer/fileserver/server.go
installer/fileserver/tasks.go

Cherry-picks commit eaa021f52e2f4c66dea1ab1d375f6d1b93b2f3fb from #759.

Add error and logging UX improvements for PSC

---

docs/user_doc/vic_vsphere_admin/set_up_ops_user.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/753
@hickeng can you please review?

Added new permission for ops user

---

docs/user_doc/vic_cloud_admin/create_projects.md
docs/user_doc/vic_overview/introduction.md

Fix for the viewer user access in VIC 1.2

---

docs/user_doc/vic_vsphere_admin/configure_vch.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/715.
@emlin and @rajanashok can you please review?

Reverted default debug level to 0

---

installer/fileserver/files/open_source_license.txt

Cherry picks 1c29e17fa1d0da198acc09e78d47913427c8560c
From PR #775

Update open source license

---

docs/user_doc/vic_overview/introduction.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Towards https://github.com/vmware/vic-product/issues/740

Added that appliances can share a PSC

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_cloud_admin/access_project_logs.md
docs/user_doc/vic_cloud_admin/add_cloud_admins.md
docs/user_doc/vic_cloud_admin/add_repos_in_portal.md
docs/user_doc/vic_cloud_admin/add_users.md
docs/user_doc/vic_cloud_admin/create_projects.md
docs/user_doc/vic_cloud_admin/create_replication_endpoints.md
docs/user_doc/vic_cloud_admin/create_replication_rules.md
docs/user_doc/vic_cloud_admin/manage_projects.md
docs/user_doc/vic_cloud_admin/manage_replication_endpoints.md
docs/user_doc/vic_overview/introduction.md

- Fixes #336
- Fixes #558 
- Fixes #298.

Mppoceduresfix3

---

docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/265
@hmahmood can you please review? Thanks!

Fixing error in management-gateway doc

---

docs/user_doc/vic_vsphere_admin/deploy_vch_registry.md
docs/user_doc/vic_vsphere_admin/vch_installer_examples.md
docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/322
@sflxn can you please take a look? Thanks!

Added docs about whitelist-registry

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Fixes https://github.com/vmware/vic-product/issues/742. @pdaigle does this do it? Thanks!

Added warning about SSHing into the appliance

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Fixes https://github.com/vmware/vic-product/issues/791

Documented to move disk during upgrade

---

installer/fileserver/html/index.html
installer/fileserver/server.go
installer/fileserver/tasks.go

Add PSC domain field to Getting Started

---

installer/packer/scripts/admiral/configure_admiral.sh
installer/packer/vic-unified.ovf

Add CA cert option to OVA deploy

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/ts_register_psc_fails.md

Fixes https://github.com/vmware/vic-product/issues/808

Documented PSC workaround

---

docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixes https://github.com/vmware/vic-product/issues/833. @hmahmood can you please review? Do we need to add anything else? 
Also, https://github.com/vmware/vic/issues/4861 talks about the logs being on the appliance, but are we actually talking about the VCH endpoint VM here? Thanks!

Added --syslog-address option

---

docs/user_doc/vic_vsphere_admin/deploy_demo_vch.md

Fixes https://github.com/vmware/vic-product/issues/772. 
@mdubya66 @morris-jason and @corrieb can you please review, and if necessary, list any additional limitations in this PR?

Documented demo VCH limitations

---

docs/user_doc/vic_cloud_admin/add_repos_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_fullTLS_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_noTLS_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_serversideTLS_in_portal.md
docs/user_doc/vic_cloud_admin/vchs_and_mgmt_portal.md
docs/user_doc/vic_overview/introduction.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Also added a limitation that you can only register a VCH with one instance of MP.
Towards https://github.com/vmware/vic-product/issues/740.
@mlh78750 can you please review?

Removed limitation of one VIC appliance per VC

---

docs/user_doc/vic_vsphere_admin/vch_installer_options.md

Fixed irritating typo

---

installer/BUILD.md
installer/Makefile
installer/packer/packer-vic.json
installer/packer/scripts/filesystem_provisioning.sh
installer/packer/scripts/provision_admiral.sh
installer/packer/scripts/provision_fileserver.sh
installer/packer/scripts/provision_harbor.sh
installer/packer/scripts/upgrade/upgrade_1.1_to_1.2.sh
installer/packer/vic-unified.ovf
installer/scripts/build.sh

Add version file to system disk and data disk
```
root@localhost [ ~ ]# cat /etc/vmware/version 
ova=v1.2.0-rc1-89-gf5918ab
harbor=harbor-offline-installer-v1.2.0.tgz
admiral=vmware/admiral:vic_v1.2.1 1fa8a0f5ec6d
engine=vic_1.2.1-rc1.tar.gz
root@localhost [ ~ ]# cat /data/version 
ova=v1.2.0-rc1-89-gf5918ab
harbor=harbor-offline-installer-v1.2.0.tgz
admiral=vmware/admiral:vic_v1.2.1 1fa8a0f5ec6d
engine=vic_1.2.1-rc1.tar.gz
```
Fixes #854

Add OVA version

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_app_dev/build_push_images.md
docs/user_doc/vic_app_dev/configure_docker_client.md
docs/user_doc/vic_app_dev/dchphoton_options.md
docs/user_doc/vic_app_dev/photon_cert_custom.md
docs/user_doc/vic_app_dev/photon_cert_manual.md
docs/user_doc/vic_app_dev/test_photon.md
docs/user_doc/vic_vsphere_admin/deploy_vch_registry.md

@corrieb I have done a stylistic pass over your dch-photon rewrites and broken it into separate topics. Can you please review? 
Thanks!

Updated new photon content from @corrieb

---

installer/packer/scripts/upgrade/upgrade.sh

This commit modifies and renames the `upgrade_1.1_to_1.2.sh` script
to `upgrade.sh`. The script now supports upgrading from `1.2.x` to
`1.2.y` as well.
The script now detects the presence of Admiral's PSC config file
(`/data/admiral/configs/psc-config.properties`) to detect the version
of the older OVA. If this file exists on the data disk, the OVA must
be of version `1.2.x`. Then, data migration is skipped but Harbor's
address is updated in Admiral's configuration.
Fixes #839

Add support for upgrading OVA 1.2.x to 1.2.y

---

installer/packer/packer-vic.json

Updates the filename in packer.

Update upgrade script file in packer

---

tutorials/README.md
tutorials/dch-swarm.sh

New dch swarm tutorial

---

installer/engine_installer/server.go
installer/fileserver/server.go
installer/lib/tls.go

Bump engine_installer and fileserver to tls v1.2

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/ts_dockerlogin_error.md

Fixes https://github.com/vmware/vic-product/issues/896.
@corrieb and @lcastellano does this cover it? Thanks!

Added troubleshooting topic about docker login

---

installer/fileserver/html/css/style.css
installer/fileserver/html/index.html

This PR fixes the following Getting Started page issues:
- Credentials dialog: remove close icon
- Expand gray section to bottom of view port
- Remove horizontal scrollbar

Fix Getting Started page UX issues

---

installer/build/scripts/harbor/start_harbor.sh
installer/build/scripts/systemd/appliance/vic-appliance-environment.sh
installer/build/vic-unified.ovf

API always runs on 8443 now
Tested with deployed ova
```
chin@CORPORATE:~|⇒  curl -k https://10.160.193.206:8443/container/version
v1.2.0-rc1-0-68b5a25e%
```

Remove vic-machine-server port config

---

docs/user_doc/vic_cloud_admin/manage_projects.md

Content trust enabling on a per project level

---

docs/user_doc/vic_app_dev/configure_docker_client.md

Addition to #299 
from the current harbor procedure:
https://github.com/vmware/harbor/blob/master/docs/user_guide.md#content-trust

Notary procedure added step for passphrases

---

installer/build/vic-unified.ovf
installer/engine_installer/html/exec.html

Update Demo VCH Installer Wizard

---

installer/DESIGN.md

VIC Appliance design doc

---

.drone.local.yml
.gitignore
tests/resources/OVA-Util.robot
tests/resources/Util.robot
tests/robot-run.sh
tests/test-cases/Group1-OVA-Install/1-01-Install.md
tests/test-cases/Group1-OVA-Install/1-01-Install.robot
tests/test-cases/Group1-OVA-Install/TestCases.md
tests/test-cases/TestGroups.md

fix for https://github.com/vmware/vic/issues/5406.
Pls note that we currently don't have VC in our CI, so these tests are not enabled in CI yet.

Implement OVA installer test

---

installer/build/scripts/systemd/network/ovf-network.service
installer/build/scripts/systemd/toolbox.service

Fixes #977 
Deployed with static IP, confirmed DCUI gets provided IP addr

Fix startup network ordering

---

installer/build/ova-manifest.json
installer/build/scripts/admiral/logging-vic.properties
installer/build/scripts/admiral/start_admiral.sh

Update admiral service unit to log to file

---

tests/resources/OVA-Util.robot
tests/resources/VC-Util.robot
tests/test-cases/Group1-OVA-Install/1-01-Install.robot

Follow up commit to make integration test more stable.

Fix test teardown with retry

---

docs/user_doc/vic_cloud_admin/vulnerability_scanning.md

Fixes https://github.com/vmware/vic-product/issues/1035. For the first three I included more than just the root of the URLs. @reasonerjt is this correct?

Corrected links to Clair DBs

---

.drone.local.yml
tests/resources/OVA-Util.robot
tests/resources/Util.robot
tests/resources/VC-Util.robot
tests/resources/VCH-Util.robot
tests/test-cases/Group1-OVA-Install/1-01-Install.md
tests/test-cases/Group1-OVA-Install/1-01-Install.robot

Add VCH test

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

- Fixes https://github.com/vmware/vic-product/issues/914
- Fixes https://github.com/vmware/vic-product/issues/942
@andrewtchin is this OK?
@mhagen-vmware can you please confirm that we only support 6.0 and 6.5 for both VC and the ESXi hosts? Thanks!

Added vSphere versions to appliance install prereqs and clarified example users

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md
docs/user_doc/vic_vsphere_admin/ts_ovf_error.md

Fixes https://github.com/vmware/vic-product/issues/961.
@andrewtchin, in https://github.com/vmware/vic-product/issues/961 you specify **Edit Settings** > **vApp Options**. As far as I can see this only appears in the Flex client. In H5, there is only a **VM Options** tab. Would going here have the same effect?

Added OVF TS topic

---

docs/user_doc/vic_vsphere_admin/access_h5_ui.md
docs/user_doc/vic_vsphere_admin/vch_portlet_ui.md
docs/user_doc/vic_vsphere_admin/verify_vch_deployment.md

@alextopuzov can you please approve?

Fixed typo

---

docs/user_doc/vic_app_dev/configuring_health_checks.md
docs/user_doc/vic_app_dev/provision_containers_portal.md

Expanding the health checks doc

---

tests/resources/VCH-Util.robot

Changes due to default logrus format in VCH.

Update for new vch logs

---

docs/user_doc/vic_app_dev/container_limitations.md

Fixes https://github.com/vmware/vic-product/issues/850. @sflxn is this correct? Thanks!

Fixed certificate names per customer request

---

installer/build/build.sh
installer/ovatools/rpctool/main.go

This change includes the VIC build number in the version string.
Fixes https://github.com/vmware/vic-ui/issues/85

Include build number in product version

---

installer/build/scripts/systemd/admiral/admiral.service
installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh

Create vic-machine-server log directory.

---

installer/build/scripts/systemd/admiral/admiral.service
installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh

Cherry picks dc30d5f1e126d1ffca890c883d8d4a624de6053c

Create vic-machine-server log directory. (#1147)

---

docs/user_doc/vic_vsphere_admin/container_networks.md
docs/user_doc/vic_vsphere_admin/vch_networking.md

Towards https://github.com/vmware/vic-product/issues/749, but need to verify that no other instances of this limitation are present.

Removed limitation that at least 2 networks must share interface

---

installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh

Add mkdir for certs directory (#1163)

---

installer/tagvm/tagvm.go

This removes the `vic-ova-identifier` custom attribute from the OVA.

Remove custom attribute tag

---

installer/tagvm/tagvm.go

This change removes the `vic-ova-identifier` custom attribute tag.

Remove custom attribute tag (#1161)

---

docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_windows.md
docs/user_doc/vic_vsphere_admin/upgrading_vic.md

Fixes https://github.com/vmware/vic-product/issues/1127. 
@lgayatri and @jooskim can you please review? You can see the full versions of the upgraded topics here:
- [Windows](https://github.com/stuclem/vic-product/blob/flexupgrade/docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_windows.md)
- [VCSA](https://github.com/stuclem/vic-product/blob/flexupgrade/docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md)

Removed the steps to restart Flex clients, updated versions.

---

installer/build/scripts/upgrade/upgrade-admiral.sh
installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Cherry pick: Upgrade script handles chained upgrades  (#1169)

---

installer/fileserver/html/index.html

Update doc links in Getting Started page to point to the 1.3

---

installer/fileserver/html/index.html

Cherry pick: Update doc links in Getting Started page to point to the 1.3 (#1180)

---

installer/build/build.sh

Update vic machine server default tag

---

tests/manual-test-cases/Group2-OVA-Features/2-08-VIC-Upgrade.md

Updated the test doc when I ran upgrade test yesterday.

Update 2-08 VIC Upgrade test

---

installer/fileserver/html/index.html
installer/fileserver/server.go

Cherry pick for pr #1234  (Correctly show validation error when verifying login to VCSA on OVA UI)
Fixes issue #1203 
Cherry picks 4645132

Correctly show validation error when verifying login to VCSA on OVA UI (#1234)

---

installer/BUILD.md

Update readme for OVA release process

---

tutorials/dch/docker-compose.yml

Fix the memory units so that it works with Admiral

Fix the memory units so that it works with Admiral

---

installer/build/scripts/admiral/configure_admiral.sh
installer/build/scripts/fileserver/configure_fileserver.sh
installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh

Cherry picks 8c2893b1b6acea35ec24a19281d222e378a367e1 and c35b394bbddf602ef88cdb70203a7f05b2b97b6d

Cherry pick: Fix cert formatting for additional services (#1247) 

---

docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md

Fixes https://github.com/vmware/vic-product/issues/1241
Fixes https://github.com/vmware/vic-product/issues/1240
@mdubya66 and @jooskim can you please review? Thanks!

Added variables to plugin install commands, mentioned upgrade

---

installer/build/ova-manifest.json
installer/build/scripts/appliance/gather_logs.sh
installer/build/scripts/appliance/get_vic_appliance_logs.sh
installer/build/scripts/filesystem_provisioning.sh

Gather appliance logs

---

tests/resources/Docker-Util.robot
tests/resources/page-objects/Right-Context-Panel-Util.robot
tests/robot-run.sh

Rerun failed integration tests

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/appliance_logs.md
docs/user_doc/vic_vsphere_admin/log_bundles.md

- Fixes #978  
- Fixes #1128
- Fixes #1155
- Fixes #1065
- Fixes #950 
I couldn't find information how to configure vic-machine-server logs. @morris-jason can you help with that?
Also I'd appreciate if more people have a look and add more info as needed.
Thank you.

Logs story update

---

docs/user_doc/vic_app_dev/provision_containers_portal.md
docs/user_doc/vic_overview/introduction.md

containers and container VM and infra containers clarification

---

docs/user_doc/vic_cloud_admin/configure_system.md
docs/user_doc/vic_cloud_admin/create_replication_endpoints.md
docs/user_doc/vic_cloud_admin/create_replication_rules.md

Replication Rule Cert fix

---

docs/user_doc/vic_vsphere_admin/pre_upgrade_tasks.md
docs/user_doc/vic_vsphere_admin/upgrading_vic.md

Quick fix as per what we just discussed.

Quick version update

---

docs/user_doc/vic_vsphere_admin/access_h5_ui.md
docs/user_doc/vic_vsphere_admin/remove_vch.md
docs/user_doc/vic_vsphere_admin/vch_portlet_ui.md
docs/user_doc/vic_vsphere_admin/verify_vch_deployment.md

- Fixes https://github.com/vmware/vic-product/issues/1193
- Fixes https://github.com/vmware/vic-product/issues/1280
@zjs is this OK? Thanks!

Added how to delete VCHs and download certs in UI

---

docs/user_doc/vic_vsphere_admin/backup_vic_appliance.md
docs/user_doc/vic_vsphere_admin/reconfigure_appliance.md

- Fixes https://github.com/vmware/vic-product/issues/967.
- Fixes https://github.com/vmware/vic-product/issues/1237
@morris-jason and @andrewtchin  is this OK? Do we need to add details of which disk is attached to which virtual device node?

Documented the 4 disks on the appliance

---

docs/user_doc/vic_app_dev/deploy_single_containervm.md

This makes a bunch of updates that should have been made as part of #511. 
In addition, makes some small updates to address #949 for this page.

Remove haveged examples. Fixes #1301

---

docs/user_doc/vic_overview/introduction.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/restart_services.md
docs/user_doc/vic_vsphere_admin/security_reference.md
docs/user_doc/vic_vsphere_admin/service_status.md

- Fixes https://github.com/vmware/vic-product/issues/947
- Fixes https://github.com/vmware/vic-product/issues/923
@zjs is this OK? Thanks!

Added that vic_machine_server runs as service in appliance

---

installer/build/baseimage/install.sh

Add missing net-tools package

---

installer/ovatools/vic-ova-ui/main.go

Update DCUI Getting Started Page link

---

installer/Makefile
installer/build/ova-manifest.json
installer/build/scripts/filesystem_provisioning.sh
installer/build/scripts/system_settings.sh
installer/build/scripts/systemd/appliance/ova-firewall.sh
installer/build/scripts/systemd/fileserver/fileserver.service
installer/build/scripts/systemd/landing_server/landing_server.service
installer/landing_server/html/index.html
installer/landing_server/server.go

Starts webserver on 80 that is stopped when Getting Started Page is ready.
I will update DCUI in a separate PR.
```
root@Photon [ ~ ]# systemctl status landing_server
● landing_server.service - VIC Appliance Landing Page Server
Loaded: loaded (/usr/lib/systemd/system/landing_server.service; enabled; vendor preset: enabled)
Active: active (running) since Fri 2018-01-12 17:45:34 UTC; 27s ago
Docs: https://github.com/vmware/vic-product
Main PID: 399 (ova-landing-ser)
Tasks: 5
Memory: 3.9M
CPU: 13ms
CGroup: /system.slice/landing_server.service
└─399 /usr/local/bin/ova-landing-server
Jan 12 17:45:34 Photon systemd[1]: Started VIC Appliance Landing Page Server.
root@Photon [ ~ ]# systemctl list-jobs
JOB UNIT                                     TYPE  STATE
96 fileserver.service …
```

Temporary landing page

---

installer/ovatools/vic-ova-ui/main.go

Cherry picks 88b8d249 
From PR #1315

Update DCUI Getting Started Page link (#1315)

---

README.md
installer/README.md
installer/SUPPORT.md

Add VIC Appliance support guide

---

installer/build/build.sh

Only select offline installer files

Update harbor build selection

---

installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Don't run Harbor upgrade if old OVA version is 1.3.0
Fixes #1321

Update upgrade script version detection

---

installer/build/baseimage/install.sh
installer/build/baseimage/stage.sh

Fixes #1345, progress to #1341.
Allows access to [password reset](https://github.com/vmware/photon/blob/master/docs/photon-os-troubleshooting-guide.md#resetting-a-lost-root-password) and other nifty photon grub _things_.

Increase grub timeout.

---

installer/build/scripts/admiral/configure_admiral.sh
installer/build/scripts/fileserver/configure_fileserver.sh
installer/build/scripts/vic_machine_server/configure_vic_machine_server.sh

Add appliance hostname to SAN for self signed certs

---

installer/build/scripts/harbor/start_harbor.sh
installer/build/scripts/systemd/harbor/harbor_startup.service
installer/build/scripts/upgrade/upgrade-admiral.sh
installer/build/scripts/upgrade/util.sh
tests/test-cases/Group1-OVA-Install/1-01-Install.robot

Add retries for some upgrade tasks

---

installer/build/scripts/admiral/configure_admiral.sh
installer/build/scripts/fileserver/configure_fileserver.sh
installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh

Cherry picks: 5aecde36
From PR: #1378

Add appliance hostname to SAN for self signed certs (#1378)

---

docs/user_doc/vic_vsphere_admin/backup_vic_appliance.md
docs/user_doc/vic_vsphere_admin/pre_upgrade_tasks.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Fixes https://github.com/vmware/vic-product/issues/1382
@morris-jason and @andrewtchin can you please review?

Updated upgrade doc for 1.3.1

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/container_networks.md
docs/user_doc/vic_vsphere_admin/deploy_vch_client.md
docs/user_doc/vic_vsphere_admin/running_vicmachine_cmds.md
docs/user_doc/vic_vsphere_admin/set_up_ops_user.md
docs/user_doc/vic_vsphere_admin/tls_unrestricted.md
docs/user_doc/vic_vsphere_admin/vch_cert_options.md
docs/user_doc/vic_vsphere_admin/vch_registry.md
docs/user_doc/vic_vsphere_admin/vch_security.md

- Fixes https://github.com/vmware/vic-product/issues/1387
- Fixes https://github.com/vmware/vic-product/issues/1305
@jooskim can you please review the UI-based changes?
@lcastellano can you please review the changes in set_up_ops_user.md? Thanks in advance!

Updated doc to reflect Create VCH wizard changes in 1.3.1

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Added explanatory note warning that procedures are different depending on upgrade path.

Added note about different numbers of disks depending on version

---

installer/SUPPORT.md

Update support doc

---

installer/build/scripts/systemd/scripts/support/appliance-support.sh

Don't exit if find doesn't find things

Update appliance support script

---

CONTRIBUTING.md

Add more details on how to submit issues

adding pointer to vic repo for detailed bug submissions

---

installer/build/scripts/upgrade/upgrade-admiral.sh

Script would previously exit on this increment

Fix retry behavior in Admiral upgrade

---

docs/user_doc/vic_vsphere_admin/plugins_vcsa.md

Folder `vic` is not in root directory but in the root home folder after following guide.

Fix small inconsistency

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

No associated issue. @andrewtchin does this cover it? Thanks!

Mentioned new initializing screen

---

installer/build/scripts/systemd/scripts/psc/get_token.sh

```
root@Photon [ /storage/data/certs ]# ls -al
total 48
drwxr-x--- 2 10000 10000 4096 Mar  1 21:31 .
drwxr-xr-x 7 root  root  4096 Mar  1 21:15 ..
-rw------- 1 10000 10000 2134 Mar  1 21:31 ca.crt
-rw------- 1 root  root  3276 Mar  1 21:31 ca.key
-rw------- 1 root  root    17 Mar  1 21:31 ca.srl
-rw------- 1 root  root    12 Mar  1 21:31 cert_gen_type
-rw------- 1 root  root    33 Mar  1 21:31 extfile.cnf
-rw------- 1 10000 10000 4155 Mar  1 21:31 server.crt
-rw------- 1 root  root  1728 Mar  1 21:31 server.csr
-rw------- 1 10000 10000 3272 Mar  1 21:31 server.key
-rw------- 1 root  root  1604 Mar  1 21:31 trustedcertificates.jks
```
```
root@Photon [ /etc/vmware/psc ]# ls -al
total 24
drwxr-xr-x 5 root  root  4096 Mar  1 21:15 .
drwxr-xr-x 9 root  root  4096 Mar  1 21:33 ..
drw------- 2 …
```

Set mode for PSC config files

---

installer/docs/SUPPORT.md

Add Harbor support information

---

installer/build/scripts/upgrade/upgrade.sh

Add govc datacenter variable for multi-dc upgrades

---

docs/user_doc/vic_app_dev/container_operations.md
docs/user_doc/vic_app_dev/creating_containerized_app_with_vic.md
docs/user_doc/vic_app_dev/deploy_multiple_docker_compose.md
docs/user_doc/vic_app_dev/deploy_single_containervm.md
docs/user_doc/vic_app_dev/docker_compose_file_options.md
docs/user_doc/vic_app_dev/putting_apps_into_production.md
docs/user_doc/vic_app_dev/vic_in_build_pipeline.md

Towards https://github.com/vmware/vic-product/issues/1453
PR includes a bit of product-name cleanup too.

Updated Docker compose version

---

tests/robot-indices/BuiltIn.index
tests/robot-indices/Collections.index
tests/robot-indices/DateTime.index
tests/robot-indices/OperatingSystem.index
tests/robot-indices/Process.index
tests/robot-indices/SSHLibrary.index
tests/robot-indices/Selenium2Library.index
tests/robot-indices/String.index

I had started this branch more than 5 months ago, most of it was done by others in that time except this piece.

Development files for robot

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-02-OVA-Upgrade.robot
tests/vic-product-nightly.sh

The service account is currently broken in nimbus, I have a helpnow ticket open already.  This fully converts the jenkins job to being entirely just run the script.  And provides the selenium resources needed to run the tests.

Finalize jenkins changes for the nightly job

---

docs/user_doc/vic_app_dev/using_volumes_with_vic.md

Added missing header to jump list at top of topic.

Added header to jump list

---

installer/docs/SUPPORT.md

Add network and console troubleshooting information

---

docs/user_doc/vic_vsphere_admin/interop.md

Fixes https://github.com/vmware/vic-product/issues/1491

Stated that vRA 7.3 doesn't support this release

---

docs/user_doc/vic_vsphere_admin/interop.md

Fixes https://github.com/vmware/vic-product/issues/1491 for the 1.2 docs.

Adding vRA interop caveat to 1.2 docs

---

docs/user_doc/vic_vsphere_admin/ts_ui_not_appearing.md

Fixes https://github.com/vmware/vic-product/issues/1443. Since we already have a troubleshooting topic for non-appearing UI problems, I integrated this info in there rather than creating a new topic. 
@jooskim does this do it?

Added link to UI bug KB

---

installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Tested 1.3.1 to 1.4.0
Adds more debug logging
Handles datastores with spaces in name when moving disks

VIC appliance upgrade improvements

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/ova_reg_api.md

Fixes https://github.com/vmware/vic-product/issues/577

 Documented OVA registration API

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md
docs/user_doc/vic_vsphere_admin/ts_recover_password.md

Fixes https://github.com/vmware/vic-product/issues/1389.
@andrewtchin is this OK? Thanks!

Adding doc about password recovery

---

installer/Makefile
installer/build/ova-manifest.json
installer/build/scripts/fileserver/fileserver.service
installer/build/scripts/provisioners/filesystem_provisioning.sh
installer/build/scripts/provisioners/system_settings.sh
installer/build/scripts/systemd/scripts/ova-firewall.sh
installer/build/scripts/systemd/units/landing_server.service
installer/landing_server/html/index.html
installer/landing_server/server.go

Fixes #1501
Cherry picks: 79a5526
From PR: #1310

Add temporary loading page before fileserver (#1310)

---

.drone.yml
tests/resources/VC-Util.robot
tests/resources/VCH-Util.robot

Include VCH logs in CI build

---

docs/user_doc/vic_vsphere_admin/security_reference.md

Fixed broken link

---

installer/build/scripts/provisioners/provision_govc.sh

Update govc to release version

---

installer/build/scripts/fileserver/configure_fileserver.sh
installer/fileserver/html/index.html
installer/landing_server/html/index.html

Update doc links to 1.4

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-03-Multiple-Datacenter.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-03-Multiple-Datacenter.robot

Fix for https://github.com/vmware/vic-ui/issues/399

Complete nightly test for multiple datacenter

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-12-Multiple-VLAN.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-12-Multiple-VLAN.robot
tests/resources/Util.robot

Fix for https://github.com/vmware/vic-ui/issues/406

Complete nightly test for multi vlan

---

tests/resources/page-objects/Container-Hosts-Page-Util.robot
tests/resources/page-objects/Registries-Page-Util.robot

Fix for https://github.com/vmware/vic-product/issues/1576

Remove text verifications for pages in tests

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-05-Enhanced-Linked-Mode.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-05-Enhanced-Linked-Mode.robot

Fix for https://github.com/vmware/vic-ui/issues/412

Complete nightly test for enhanced link mode

---

.gitignore
installer/build/scripts/systemd/scripts/vic-appliance-tls.sh
installer/docs/DESIGN.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-02-OVA-Upgrade.robot
tests/manual-test-cases/Group6-OVA-TLS/6-01-OVA-TLS.md
tests/manual-test-cases/Group6-OVA-TLS/6-01-OVA-TLS.robot
tests/manual-test-cases/Group6-OVA-TLS/TestCases.md
tests/manual-test-cases/README.md
tests/manual-test-cases/TestGroups.md
tests/resources/Cert-Util.robot
tests/resources/OVA-Util.robot
tests/resources/Util.robot

Add appliance TLS tests to nightly

---

docs/user_doc/vic_vsphere_admin/access_h5_ui.md
docs/user_doc/vic_vsphere_admin/deploy_vch_client.md
docs/user_doc/vic_vsphere_admin/install_vic_plugin.md
docs/user_doc/vic_vsphere_admin/plugins_vc_windows.md
docs/user_doc/vic_vsphere_admin/plugins_vcsa.md
docs/user_doc/vic_vsphere_admin/reconfigure_appliance.md
docs/user_doc/vic_vsphere_admin/uninstall_vic.md
docs/user_doc/vic_vsphere_admin/vch_admin_client.md
docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md

 Added support for vSphere 6.7 and  verified plugin installation

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/pre_upgrade_tasks.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance_manual.md
docs/user_doc/vic_vsphere_admin/upgrade_h5_plugin_vcsa.md

Fixes https://github.com/vmware/vic-product/issues/1470. I tested upgrade from 1.3.1 to 1.4.0, both with and without manual migration of the disks. I haven't tested 1.2.1 upgrade yet. 
@morris-jason and @andrewtchin can you please review? Thanks!

Updated upgrade docs for 1.4

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-8-DRS.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-8-DRS.robot

Complete nightly test for DRS

---

docs/user_doc/vic_vsphere_admin/interop.md

Fixes https://github.com/vmware/vic-product/issues/1491

Updated vRA support info

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-8-DRS.robot

Fix Nightly DRS test

---

tutorials/selenium/docker-compose-harbor.yaml

Updating the image location to Harbor
Fixes #

Create a Docker-compose file for Selenium to pull images from Harbor

---

docs/user_doc/vic_vsphere_admin/access_h5_ui.md

Fixes https://github.com/vmware/vic-product/issues/1614. @zjs can you please review?

Removed limits on deleting VCHs from UI

---

docs/user_doc/vic_vsphere_admin/interop.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md

Towards https://github.com/vmware/vic-product/issues/1491 and fixes https://github.com/vmware/vic-product/issues/1561.

Added links to interop matrix, and minor rewording

---

tests/resources/page-objects/Project-Repositories-Page-Util.robot
tests/test-cases/Group4-Harbor/4-01-Harbor.robot

Fix new harbor UI breaks testcase
Fixes #1632

Update Harbor UI test

---

docs/user_doc/vic_vsphere_admin/configure_vch.md

Fixes https://github.com/vmware/vic-product/issues/1461. @gigawhitlocks can you please review? Thanks!

Restoring doc about vic-machine configure --tls-cname

---

tests/resources/page-objects/Project-Repositories-Page-Util.robot
tests/test-cases/Group4-Harbor/4-01-Harbor.robot

Cherry picks: 19d8babd
From PR: #1633

Update Harbor UI test (#1633)

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/vic_cert_reference.md

- Fixes https://github.com/vmware/vic-product/issues/1600
- Fixes https://github.com/vmware/vic-product/issues/818

Added info about intermediate CAs for appliance cert

---

docs/user_doc/vic_cloud_admin/add_project_registry.md
docs/user_doc/vic_cloud_admin/add_vch_fullTLS_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_noTLS_in_portal.md
docs/user_doc/vic_cloud_admin/add_vch_serversideTLS_in_portal.md
docs/user_doc/vic_cloud_admin/create_projects.md
docs/user_doc/vic_cloud_admin/create_replication_endpoints.md
docs/user_doc/vic_cloud_admin/create_replication_rules.md
docs/user_doc/vic_cloud_admin/manage_replication_endpoints.md

Fixed UI string changes

---

installer/docs/BUILD.md
installer/docs/RELEASE.md

Update release procedures

---

.github/ISSUE_TEMPLATE.md
installer/docs/SUPPORT.md

Update issue template

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-8-DRS.robot
tests/manual-test-cases/Group7-Upgrade/7-01-Upgrade-1.2.1.robot
tests/resources/OVA-Util.robot

Fixes for the issues seen on last Jenkins build.

Fix nightly test issues

---

installer/build/scripts/provisioners/provision_harbor.sh

Cherry picks: 8162757
From PR: #1677

Use restart policy always for Harbor jobservice (#1677)

---

tests/manual-test-cases/Group2-OVA-Features/2-05-Static-IP.md
tests/manual-test-cases/Group2-OVA-Features/2-05-Static-IP.robot
tests/resources/Nimbus-Util.robot
tests/resources/OVA-Util.robot

Add nightly test for static ip

---

installer/build/bootable/build-base.sh
installer/build/scripts/systemd/scripts/support/appliance-support.sh
installer/build/scripts/upgrade/upgrade-harbor.sh
installer/build/scripts/upgrade/upgrade.sh

Cherry picks: ec49f84
From PR: #1601

Appliance upgrade non-interactive flags (#1601)

---

installer/build/scripts/systemd/scripts/support/appliance-support.sh

Cherry picks: dab699e
From PR: #1671

Filter private values in appliance support bundle (#1671)

---

installer/build/scripts/upgrade/upgrade.sh

Cherry picks: 4d47ec0
From PR: #1681

Fix upgrade script variable (#1681)

---

installer/build/scripts/upgrade/upgrade.sh

Update unsupported upgrade path message

---

tests/vic-product-nightly.sh

This will facilitate to add nightly build for releases.

Update nightly script to run for any GCS bucket

---

tests/manual-test-cases/Group2-OVA-Features/2-05-Static-IP.robot
tests/resources/Docker-Util.robot
tests/resources/OVA-Util.robot
tests/vic-product-nightly.sh

Mounts host docker daemon and certs dir instead of using DIND. Plus one typo fix with keyword name.

Fix nightly tests dockerd issues

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance_manual.md

Fixes https://github.com/vmware/vic-product/issues/1608
@andrewtchin and @morris-jason can you please review? Thanks!

Documented CLI arguments for upgrade script

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/ts_deploy_appliance.md
docs/user_doc/vic_vsphere_admin/ts_reg_doesnt_start.md

Fixes https://github.com/vmware/vic-product/issues/1655

Added TS topic about deploying OVA using 6.7 H5 client

---

tests/manual-test-cases/Group2-OVA-Features/TestCases.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-08-DRS.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-08-DRS.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-09-Network-Folder.robot
tests/manual-test-cases/Group5-Interoperability-Tests/TestCases.md
tests/manual-test-cases/TestGroups.md

Fix test documentation for Nightlies and rename DRS files as per standards.

Fix nightly tests documentation

---

tests/resources/OVA-Util.robot

Retrying UI steps as they tend to be brittle

Retry UI steps for nightly tests

---

installer/build/build-cache.sh

harbor registry version fix

---

installer/build/bootable/build-base.sh

Pin docker version to 17.21

---

installer/build/bootable/build-base.sh

Pin ova docker version to 17.21 (#1715)

---

.drone.yml
installer/build/build-ova.sh
installer/build/container/Dockerfile
installer/scripts/ci-build.sh

Fixes #397. Relies on vmware/vic#7852.

Pull release version of vic-machine-server

---

tests/manual-test-cases/Group2-OVA-Features/2-05-Static-IP.robot
tests/resources/Nimbus-Util.robot
tests/resources/OVA-Util.robot

- Fix for static ip test #1710
- Update nimbus keywords for `NIMBUS_LOCATION`
- Update `Create Simple VC Cluster With Static IP` keyword to use Mike's testbed setup

Fix nightly static ip test

---

docs/user_doc/vic_vsphere_admin/vch_general_settings.md

Clarified that you can add prefix and suffix to cVMs

---

docs/user_doc/vic_cloud_admin/create_replication_endpoints.md
docs/user_doc/vic_cloud_admin/create_replication_rules.md
docs/user_doc/vic_cloud_admin/manage_replication_endpoints.md

Fixing vertical dots in the UI disappearance 
Fixing replication enpoints procedures

Fixed replication endpoints and vertical dots

---

tests/vic-product-nightly.sh

Updates nightly script for:
- Retry OVA download on failure 
- Exit if OVA download fails

Retry OVA download for nightlies

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot

Update nightly VSAN test to use common keyword as used in rest of the tests.

Update nightly VSAN test

---

installer/build/build-ova.sh

Use stable master build link for harbor

---

installer/docs/design/ui-plugin-install-technical.md
installer/docs/design/ui-plugin-install.md

Fixes #1720.
This document outlines the approach for adding thumbprint verification and plugin install steps to the ui. 
Please review the approach `## Purposed Design.`

Automated VIC UI Plugin Technical Design

---

tutorials/custom_certificate/README.md

Tutorial on how to create custom certificate for VCH

Tutorial - Custom Certificates for VCHs

---

installer/docs/DESIGN.md

Update design doc [skip ci]

---

docs/user_doc/vic_app_dev/provision_containers_portal.md
docs/user_doc/vic_cloud_admin/vchs_and_mgmt_portal.md
docs/user_doc/vic_vsphere_admin/vch_registry.md

Fixes https://github.com/vmware/vic-product/issues/1651. @lazarin and @pdaigle can you please review?

Added notes about VCH whitelists vs MP Registry lists

---

docs/user_doc/vic_cloud_admin/working_with_registries.md

Will add VIC specific procedure post 1.4 GA,

removed link to procedure in github postGA fix

---

docs/user_doc/vic_vsphere_admin/configure_vch.md

Fixes https://github.com/vmware/vic-product/issues/1656. @zjs can you please review?

Added vic-machine configure --ops-grant-perms

---

installer/build/scripts/upgrade/upgrade.sh

Update old appliance prompt

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance_manual.md

Per chat with @morris-jason, we got it wrong in https://github.com/vmware/vic-product/pull/1747.

Fixed FQDN statements for upgrade script

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-08-DRS.robot

Retry UI steps for nightly DRS test

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-06-2-VSAN-Complex.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-06-2-VSAN-Complex.robot
tests/resources/OVA-Util.robot
tests/resources/VC-Util.robot
tests/resources/VCH-Util.robot
tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Add nightly test for complex VSAN

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-06-2-VSAN-Complex.robot

Add missing VCH_TIMEOUT var

---

tests/vic-product-nightly.sh

Nightly ova download on every try

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-17-FC-Datastore.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-17-FC-Datastore.robot

Add nightly test for FC datastore

---

tests/vic-product-nightly.sh

Fix wget command in nightly script

---

docs/user_doc/vic_app_dev/using_volumes_with_vic.md
docs/user_doc/vic_vsphere_admin/volume_stores.md

Fixes https://github.com/vmware/vic-product/issues/1464 (again) adding more info from @dbarkelew. 
@dbarkelew and @matthewavery can you please review?

Adding more info about root squash for NFS

---

docs/user_doc/vic_app_dev/book.json
docs/user_doc/vic_app_dev/node_modules/gitbook-plugin-noembed/.npmignore
docs/user_doc/vic_app_dev/node_modules/gitbook-plugin-noembed/README.md
docs/user_doc/vic_app_dev/node_modules/gitbook-plugin-noembed/assets/scripts.js
docs/user_doc/vic_app_dev/node_modules/gitbook-plugin-noembed/assets/style.css
docs/user_doc/vic_app_dev/node_modules/gitbook-plugin-noembed/index.js
docs/user_doc/vic_app_dev/node_modules/gitbook-plugin-noembed/package.json
docs/user_doc/vic_cloud_admin/book.json
docs/user_doc/vic_cloud_admin/node_modules/gitbook-plugin-noembed/.npmignore
docs/user_doc/vic_cloud_admin/node_modules/gitbook-plugin-noembed/README.md
docs/user_doc/vic_cloud_admin/node_modules/gitbook-plugin-noembed/assets/scripts.js
docs/user_doc/vic_cloud_admin/node_modules/gitbook-plugin-noembed/assets/style.css
docs/user_doc/vic_cloud_admin/node_modules/gitbook-plugin-noembed/index.js
docs/user_doc/vic_cloud_admin/node_modules/gitbook-plugin-noembed/package.json
docs/user_doc/vic_overview/book.json
docs/user_doc/vic_overview/node_modules/gitbook-plugin-noembed/.npmignore
docs/user_doc/vic_overview/node_modules/gitbook-plugin-noembed/README.md
docs/user_doc/vic_overview/node_modules/gitbook-plugin-noembed/assets/scripts.js
docs/user_doc/vic_overview/node_modules/gitbook-plugin-noembed/assets/style.css
docs/user_doc/vic_overview/node_modules/gitbook-plugin-noembed/index.js
docs/user_doc/vic_overview/node_modules/gitbook-plugin-noembed/package.json
docs/user_doc/vic_vsphere_admin/book.json
docs/user_doc/vic_vsphere_admin/node_modules/gitbook-plugin-noembed/.npmignore
docs/user_doc/vic_vsphere_admin/node_modules/gitbook-plugin-noembed/README.md
docs/user_doc/vic_vsphere_admin/node_modules/gitbook-plugin-noembed/assets/scripts.js
docs/user_doc/vic_vsphere_admin/node_modules/gitbook-plugin-noembed/assets/style.css
docs/user_doc/vic_vsphere_admin/node_modules/gitbook-plugin-noembed/index.js
docs/user_doc/vic_vsphere_admin/node_modules/gitbook-plugin-noembed/package.json

This should fix PDF generation with embedded videos.

Adding the noembed plugin to PDF book.json files

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch-No-Cluster.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-03-Multiple-Datacenter.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-04-Multiple-Cluster.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-05-Enhanced-Linked-Mode.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-08-DRS.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-09-Network-Folder.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-12-Multiple-VLAN.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-15-NFS-Datastore.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-16-vMotion-VCH-Appliance.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-17-FC-Datastore.robot
tests/resources/Nimbus-Util.robot
tests/resources/OVA-Util.robot
tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Fix nightly DRS test and remove TEST_TIMEOUT var

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch-No-Cluster.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-04-Multiple-Cluster.robot
tests/resources/Nimbus-Util.robot
tests/resources/UI-Util.robot
tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Fixes rest of #1776 and https://github.com/vmware/vic-ui/issues/474

Fix nightly test issue for datastore UI

---

docs/user_doc/vic_vsphere_admin/appliance_logs.md

Fixes #1741.
@morris-jason and @lazarin I have a couple of open questions in https://github.com/vmware/vic-product/issues/1741. Thanks!

Adding more info about the appliance logs.

---

installer/fileserver/main.go
installer/fileserver/routes/index.go
installer/fileserver/routes/plugin.go
installer/fileserver/routes/register.go
installer/fileserver/routes/renderer.go
installer/fileserver/routes/thumbprint.go
installer/fileserver/tasks/ova/configure.go
installer/fileserver/tasks/ova/configure_test.go
installer/fileserver/tasks/plugin.go
installer/fileserver/tasks/plugin/register.go
installer/fileserver/tasks/plugin_test.go
installer/fileserver/tasks/register.go
installer/fileserver/tasks/tagvm/tagvm.go
installer/lib/login.go
installer/lib/tls.go

Progress to #1702, Fixes #1789
This pr implements plugin lifecycle operations through the index page and through new `/plugin` apis.
Reviewing by commit is probably easiest, as the first few commits are just copying files.

Automated VIC-UI Plugin - Install

---

installer/build/scripts/upgrade/upgrade.sh

Fixes #1702
Final change for 1702 to preform a plugin upgrade during the upgrade script.
Merge after 1779.

Preform a plugin install during the appliance upgrade

---

installer/build/scripts/upgrade/upgrade.sh
tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.0.robot

Nightly upgrade fix

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Cherry picks: 2133d84 3e8b4d3
From PR: #1816

Update upgrade script for 1.4.1

---

installer/build/bootable/root/etc/systemd/journald.conf.d/10-persistent.conf
installer/build/scripts/provisioners/provision_harbor.sh
installer/build/scripts/systemd/scripts/support/appliance-support.sh

Cherry picks: 86efc89
From PR: #1813

Fix Clair CPU Restrictions (#1813)

---

docs/user_doc/vic_app_dev/putting_apps_into_production.md
docs/user_doc/vic_app_dev/using_volumes_with_vic.md
docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
docs/user_doc/vic_vsphere_admin/deploy_vch_esxi.md

Fixes https://github.com/vmware/vic-product/issues/1612.
@dbarkelew does this better reflect the customer experience? @pdaigle can you please take a look too?
To see the topic in its entirety, rather than the diff, go [here](https://github.com/stuclem/vic-product/blob/basicvch/docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md). Thanks!

Further updates to the VCH deployment example

---

docs/user_doc/vic_vsphere_admin/configure_vch.md
docs/user_doc/vic_vsphere_admin/inspect_vch.md
docs/user_doc/vic_vsphere_admin/list_vch.md
docs/user_doc/vic_vsphere_admin/remove_vch.md
docs/user_doc/vic_vsphere_admin/upgrade_vch.md

Fixes https://github.com/vmware/vic-product/issues/1754. 
The new info about `vic-machine configure --affinity-vm-group` is in https://github.com/vmware/vic-product/commit/9f4a7b8cde1350db0482af86bfa9cf7b9a9090af.
@zjs is this OK?

Adding vic-machine configure --affinity-vm-group

---

dinv/dch-photon-1.12/Dockerfile
dinv/dch-photon-1.13/Dockerfile
dinv/dch-photon-17.06/Dockerfile

Update openssl for DCH

---

docs/user_doc/vic_vsphere_admin/configure_vch.md
docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
docs/user_doc/vic_vsphere_admin/volume_stores.md

Per comment from @mavery via Slack.

 Fixed paths in NFS examples

---

docs/user_doc/vic_cloud_admin/configure_scheduled_vulnerability.md
docs/user_doc/vic_cloud_admin/configure_vulnerability_scanning_per_project.md
docs/user_doc/vic_cloud_admin/working_with_registries.md

Repositories / Internal addressed

---

installer/build/scripts/systemd/scripts/vic-appliance-environment.sh

Prevent password masking from becoming password
There is a path, likely retry or recoverying but at this time unconfirmed,
by which the password masking can be set as the password. This expressly
checks for the value having been masked and refuses to change the password
to that value.
This is a very focused change to address specifically the observed
behaviour as the implications of a revert or moving the code to other
units are not understood at this time.
Issue was introduced in 3c5cd51a

Prevent password masking from becoming password

---

README.md

Pescerosso patch 5

---

tutorials/elasticsearch/Readme.md
tutorials/elasticsearch/docker-compose.yml

Cdinkens elasticsearch tutorial

---

tutorials/spark/README.md
tutorials/spark/docker-compose.yml

Adding Spark docker-compose File

---

tests/vic-product-nightly.sh

Enhance the nightly script
Fixes #

Cherry: Remove the needless slash in gs path (#1920)

---

installer/docs/RELEASE.md

Improve examples and clarify instructions.
---

Update branching, cherry-picking, and tagging docs

---

tutorials/elk/README.md

Update ELK README.md

---

tutorials/spark/README.md

Update Spark README.md

---

tutorials/elk/README.md

updating Spelling

---

docs/user_doc/vic_users/README.md

Fixes #1904.
@vidya-v can you please review?

Edited intro blurb for devops

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Fixes #1912. Also reformatted the prereqs a little bit, to indent the bullets relating to the deployment of the new appliance.
@zjs and @pdaigle is this OK? Thanks!

Documented how to retain IP address during appliance upgrade

---

docs/user_doc/vic_vsphere_admin/common_vic_options.md
docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
docs/user_doc/vic_vsphere_admin/deploy_vch_esxi.md

Changes to the following topics:
Deploy a Virtual Container Host to an ESXi Host with No vCenter Server - Result section
Deploy a Virtual Container Host with a Volume Store and vSphere Integrated Containers Registry Access - Result section
Common vic-machine Options: --id section
Fixes #1939 
@stuclem request your review.

Made changes for Issue #1939

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_app_dev/container_limitations.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/ts_imagestore_error.md
docs/user_doc/vic_vsphere_admin/ts_post_deployment_op.md

Fixes https://github.com/vmware/vic-product/issues/1974. Luca, can you please review?

Documented issue with excessive image layers

---

tests/resources/VCH-Util.robot
tests/resources/VIC-UI-Util.robot

Fix a couple of scenario test failures.

Fix scenario test failures

---

docs/user_doc/vic_cloud_admin/manage_repository_registry.md

Added a step to add/edit a repository description
Fixes #934 
Hi @stuclem , can you please review this? 
Thanks,
Vidya

Repository description

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot
tests/resources/OVA-Util.robot
tests/resources/VC-Util.robot
tests/resources/VIC-UI-Util.robot

Searching the correct keyword to fetch vc-ip in nimbus log
Using correct datacenter name and vc name in Nimbus testbed.
Removing duplicated keywords introduced in UI auto registry code.
(cherry picked from commit 6c8a5cf5eff5f8ab800f41162a30447c09d39055)

Cherry-pick: Fixing 5-06-1-VSAN-Simple failures (#2001)

---

installer/fileserver/html/index.html
installer/fileserver/html/js/index-handler.js
installer/fileserver/tasks/plugin.go
tests/resources/page-objects/Complete-Installation-Modal-Util.robot
tests/resources/page-objects/Getting-Started-Page-Util.robot
tests/test-cases/Group2-Getting-Started/2-01-Getting-Started.robot

Fix OVA initialization UI test

---

installer/fileserver/html/index.html
installer/fileserver/html/js/index-handler.js
installer/fileserver/tasks/plugin.go
tests/resources/page-objects/Complete-Installation-Modal-Util.robot
tests/resources/page-objects/Getting-Started-Page-Util.robot
tests/test-cases/Group2-Getting-Started/2-01-Getting-Started.robot

After Fixing event parameter not declared issue in Firefox browser,
the tests can pass under Firefox.
(cherry picked from commit 8c35ac7d3f311c941931f246623f1d705f442914)
Cherry picks: 8c35ac7d3f311c941931f246623f1d705f442914
From PR: #2004

Fix OVA initialization UI test (#2004)

---

docs/user_doc/vic_vsphere_admin/ova_reg_api.md

Added thumbprint values to all examples.
Hi @stuclem @jitinkumar2018  @renmaosheng , can you please review this? Thanks!
Fixes #2029

Added thumbprint value to json payload

---

docs/user_doc/graphic_sources/VIC_Networking.ai
docs/user_doc/graphic_sources/VIC_conceptual_overview.ai

Keeping an archive of the graphic source files here, because the VIC doesn't fit in with the art department's usual archiving system.

Adding the source files for the networking and roles graphics

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/vicappliance_welcomepage_error.md

Added a new topic under [Troubleshoot vSphere Integrated Containers Appliance Deployment](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/ts_deploy_appliance.html)
Fixes #1282 
Hi @stuclem , can you please review this PR? Thanks!

Added troubleshooting topic for appliance welcome page error

---

docs/user_doc/vic_vsphere_admin/appliance_logs.md

Added `options --include-private --outdir <directory> --ignore-disk-space` to the script and restructured the topic.  I have divided the information into three different sections.
Fixes #1269 
Hi @stuclem , can you please review the changes. Thanks!

Appliancelogscript

---

docs/user_doc/vic_vsphere_admin/interop.md

Documented that vCenter Server HA is not supported.
Hi @stuclem , can you please review this PR? Thanks!
Fixes #1811

Added that vCenter Server HA is not supported

---

docs/user_doc/vic_vsphere_admin/running_vicmachine_cmds.md

Fixes https://github.com/vmware/vic-product/issues/1938

Documented vic-machine autocomplete

---

docs/user_doc/vic_vsphere_admin/vch_proxy.md
docs/user_doc/vic_vsphere_admin/vicmachine_options_ref.md

Fixes https://github.com/vmware/vic-product/issues/1928. @wjun can you please review? Thanks!

Added --no-proxy option to docs

---

installer/docs/BUILD.md
installer/docs/RELEASE.md

(cherry picked from commit 34af3ab811211748109318c7f8e2529e519c679d)

Update document to reflect vic ui build change (#2014)

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-16-vMotion-VCH-Appliance.robot

Setting the correct parameters.

Fixing failure in 5-16-vMotion-VCH-Appliance

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/deploy_vch.md
docs/user_doc/vic_vsphere_admin/ts_deploy_vch.md
docs/user_doc/vic_vsphere_admin/ts_vch_incorrect_initialization.md
docs/user_doc/vic_vsphere_admin/vch_sizing_guidelines.md

Added sizing guidelines for VCH with information from https://vmware-com.socialcast.com/messages/39074680
Fixes #1895 
Hi @stuclem , can you please review this? 
Thanks!
Vidya

Sizing guidelines

---

docs/user_doc/vic_vsphere_admin/ts_ui_not_appearing.md
docs/user_doc/vic_vsphere_admin/uninstall_vic.md

Fixes https://github.com/vmware/vic-product/issues/2062. @lgayatri since you just tested the MOB procedure, can you please review? Thanks!

Added step to restart client after removing plug-in

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/reinitialize_appliance.md

Fixes https://github.com/vmware/vic-product/issues/644.
@renmaosheng can you please review?

Documented reinitialization for client install/upgrade and PSC update

---

docs/user_doc/vic_vsphere_admin/log_bundles.md

Hi @stuclem , I have worked on Dani's comments. Can you please review the updates?
Thanks!
Fixes #2064

Worked on Dani's comments on live logs

---

docs/user_doc/vic_vsphere_admin/interop.md

Added support information for vRA 7.5.
@stuclem , can you please review this? Thanks!
Fixes #1894

Included information on vra 7.5

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Updates upgrade scripts to list 1.4.3 as a supported upgrade path.
---

Update upgrade scripts for 1.4.4

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Updates upgrade scripts to list 1.4.3 as a supported upgrade path.

Cherry-pick: Update upgrade scripts for 1.4.4 (#2122)

---

src/app/app.component.html

Added 1.4.4 release and updated RN link.

Updated for 1.4.4

---

tests/resources/page-objects/Container-Hosts-Page-Util.robot
tests/resources/page-objects/Containers-Page-Util.robot

Extend waiting time for obtaining 'card-name' element
Signed-off-by: FangyuanCheng <fangyuanc@vmware.com>
Assessment Checklist]

Fix test-case of 'Test 3-01 Admiral UI'

---

tests/manual-test-cases/Group7-Upgrade/7-01-Upgrade-1.2.1.robot
tests/manual-test-cases/Group7-Upgrade/7-02-Upgrade-1.3.0.robot
tests/manual-test-cases/Group7-Upgrade/7-03-Upgrade-1.3.1.robot
tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.0.robot
tests/resources/Nimbus-Util.robot
tests/resources/nimbus-testbeds/vic-cluster-2esxi-iscsi.rb

Create Keyword to use rubyfile to create 2 esxi with shared iscsi lun as test env
Part of fix issue #2111
Create Keyword Setup Simple VC And Test Environment with Shared iSCSI Storage
Create Keyword Create Simple VC Cluster With Spec File
Update test env in Group7-Upgrade cases to use this new test env

Create Keyword to use rubyfile to create 2 esxi with shared iscsi lun as test env

---

.github/ISSUE_TEMPLATE/defect.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/security.md
.github/ISSUE_TEMPLATE/test-failure.md

Introduce a set of issue templates for common types of issues, such as defects, documentation feedback, feature requests, questions, and test failures. Additionally, introduce as issue template for security issues that directs users to VMware's official security response policy.
Revise default template to be more appropriate for more issues that do not fall into any of these categories (e.g., infrastructure issues and tasks).
---
- n/a
- n/a
Related: vmware/vic#8280

Update GitHub issue templates

---

tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.2.1.robot
tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.3.0.robot
tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.3.1.robot
tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.4.0.robot

Use Keyword Setup Simple VC And Test Environment with Shared iSCSI Storage to set up test env
Part of fix issue#2111

[Scenario]Update Group8 related cases test env

---

installer/build/build-ova.sh

Include latest Harbor build in master branch to VIC appliance.
Fixes #

Change Harbor latest build link

---

tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Add 'https://' when setting VIC-ADMIN variable

Add https:// when setting VIC-ADMIN variable

---

docs/user_doc/book.json
docs/user_doc/vic_users/SUMMARY.md

Fixed Edit this Page button so that it points to the 1.4 branch.

Pointing the edit button to 1.4 docs

---

installer/build/ova-manifest.json
installer/build/scripts/verify.py
installer/build/scripts/verify.sh
installer/fileserver/routes/index.go

Fixes #[93](https://github.com/vmware/vic-tasks/issues/93)

Verify vic password during (re)initialization

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-12-Multiple-VLAN.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-15-NFS-Datastore.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-16-vMotion-VCH-Appliance.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-17-FC-Datastore.robot
tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.3.0.robot
tests/manual-test-cases/Group9-VIC-UI/9-2-VIC-UI-Uninstaller.robot

5-12-Multiple-VLAN.robot
5-15-NFS-Datastore.robot
5-16-vMotion-VCH-Appliance.robot
5-17-FC-Datastore.robot
8-01-Manual-Upgrade-1.3.0.robot
9-2-VIC-UI-Uninstaller.robot

Add collect log for the missing cases

---

installer/fileserver/test/fixtures/index.html
installer/fileserver/test/karma.conf.js
installer/fileserver/test/package-lock.json
installer/fileserver/test/package.json
installer/fileserver/test/specs/index-handler-spec.js

vic product will have security issues:
CVSS Base Score and Vector
https://nvd.nist.gov/vuln/detail/CVE-2017-16115
Summary: The timespan module is vulnerable to regular expression denial of service. Given 50k characters of untrusted user input it will block the event loop for around 10 seconds.
Base Score: 7.5 HIGH
Vector: AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
https://nvd.nist.gov/vuln/detail/CVE-2015-8857
Summary: The uglify-js package before 2.4.24 for Node.js does not properly account for non-boolean values when rewriting boolean expressions, which might allow attackers to bypass security mechanisms or possibly have unspecified other impact by leveraging improperly rewritten Javascript.
Base Score: 9.8 CRITICAL
Vector: AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H …

fix security issue introduced by test package

---

installer/build/scripts/upgrade/upgrade.sh
installer/fileserver/routes/plugin.go
tests/resources/VIC-UI-Util.robot

vic appliance password is part of appliance object.

Fix incorrect plugin api usage

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Fixes https://github.com/vmware/vic-product/issues/2225.
@wjun is this correct? Thanks!

Documented that appliance password is limited to 30 chars

---

installer/build/scripts/upgrade/upgrade.sh

Add vic root password into interactive mode

---

.drone.yml

Include Harbor GA build into VIC 1.5 appliance.
Fixes #

Update Harbor GA build

---

docs/user_doc/vic_app_dev/build_push_images.md
docs/user_doc/vic_app_dev/dch_expand_disk.md
docs/user_doc/vic_app_dev/dch_photon_proxy.md
docs/user_doc/vic_app_dev/dchphoton_options.md
docs/user_doc/vic_app_dev/photon_cert_custom.md
docs/user_doc/vic_app_dev/photon_cert_manual.md
docs/user_doc/vic_app_dev/test_photon.md
docs/user_doc/vic_overview/intro_to_vic_engine.md
docs/user_doc/vic_vsphere_admin/deploy_vch_dchphoton.md
docs/user_doc/vic_vsphere_admin/ova_reg_api.md
docs/user_doc/vic_vsphere_admin/ts_recover_password.md
docs/user_doc/vic_vsphere_admin/vch_install_packages.md
docs/user_doc/vic_vsphere_admin/vch_mount_nfsshare.md
docs/user_doc/vic_vsphere_admin/vic_engine_bundle.md

Fixes https://github.com/vmware/vic-product/issues/2157
@renmaosheng can you please review or assign a reviewer? Thanks!

Specified that all VIC engine components run Photon OS 2.0, updated dch-photon version.

---

installer/build/scripts/provisioners/provision_harbor.sh

2 $ in harbor.https.vic.conf , need remove one.

remove $ in nginx config of harbor

---

installer/build/scripts/upgrade/upgrade-harbor.sh

Upgrade the migrator_image from v1.6.0 to v1.7.0.

Upgrade harbor's migrator image to 1.7.0

---

tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.4.md
tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.4.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.4.4.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-01-Manual-Upgrade-1.4.4.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Add upgrade cases into Group7 and Group8

Add upgrade cases from ova 1.4.4 to the latest

---

docs/user_doc/vic_vsphere_admin/configure_vch.md
docs/user_doc/vic_vsphere_admin/image_store.md
docs/user_doc/vic_vsphere_admin/vicmachine_options_ref.md

Fixes https://github.com/vmware/vic-product/issues/2159.
@wjun is this OK? Thanks!

Documented --storage-quota option

---

docs/user_doc/vic_vsphere_admin/vch_boot_options.md

Fixes https://github.com/vmware/vic-product/issues/2158.
@DanielXiao can you please review? Thanks!

Documented alternative boot ISO

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Added link to reconfigure appliance doc in upgrade doc

---

docs/user_doc/vic_vsphere_admin/vch_compute.md

Small change not associated with an issue.

Mentioned VM-host affinity in compute resource section

---

docs/user_doc/vic_vsphere_admin/vch_storage.md

Fixes https://github.com/vmware/vic-product/issues/130
@zjs is this OK? Thanks!

Documented how to change image store

---

docs/user_doc/vic_vsphere_admin/upgrade_appliance.md
docs/user_doc/vic_vsphere_admin/upgrade_appliance_manual.md

Fixes https://github.com/vmware/vic-product/issues/2247. @wjun can you please review? Thanks!

Added step to provide new appliance password to upgrade doc

---

tutorials/concourse/README.md

Added instructions for running concourse

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Fixes https://github.com/vmware/vic-product/issues/2297. @DanielXiao can you please review? Thanks!

Added NTP server and proxies to OVA deployment doc

---

docs/user_doc/vic_app_dev/run_dev_project.md
docs/user_doc/vic_cloud_admin/vulnerability_scanning.md
docs/user_doc/vic_overview/intro_to_vic.md
docs/user_doc/vic_vsphere_admin/deploy_vch.md
docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md
docs/user_doc/vic_vsphere_admin/ts_appliance_boot_errors.md
docs/user_doc/vic_vsphere_admin/ts_appliance_running_errors.md
docs/user_doc/vic_vsphere_admin/vch_deployment_options.md

A few links got broken in the prereqs reorg

Fixed broken links

---

src/app/app.component.html

Fixes https://github.com/vmware/vic-product/issues/2300

Updated for 1.5.0 and fixed Slack joinup link

---

tests/resources/Nimbus-Util.robot

Testing delete nimbus folder for fixed https://github.com/vmware/vic-product/issues/2328

Fix issue of deleting nimbus folder

---

docs/user_doc/vic_vsphere_admin/ts_no_access_to_vic_services.md

[Issue-2118] Added reference to KB 56445

---

tests/resources/page-objects/Registries-Page-Util.robot

Fixed reference problem of variable

---

tests/manual-test-cases/Group7-Upgrade/7-05-Upgrade-1.4.4.md
tests/manual-test-cases/Group7-Upgrade/7-05-Upgrade-1.4.4.robot
tests/manual-test-cases/Group7-Upgrade/7-06-Upgrade-1.5.0.md
tests/manual-test-cases/Group7-Upgrade/7-06-Upgrade-1.5.0.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-02-Manual-Upgrade-1.3.0.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-02-Manual-Upgrade-1.3.0.robot
tests/manual-test-cases/Group8-Manual-Upgrade/8-03-Manual-Upgrade-1.3.1.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-03-Manual-Upgrade-1.3.1.robot
tests/manual-test-cases/Group8-Manual-Upgrade/8-04-Manual-Upgrade-1.4.0.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-04-Manual-Upgrade-1.4.0.robot
tests/manual-test-cases/Group8-Manual-Upgrade/8-05-Manual-Upgrade-1.4.4.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-05-Manual-Upgrade-1.4.4.robot
tests/manual-test-cases/Group8-Manual-Upgrade/8-06-Manual-Upgrade-1.5.0.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-06-Manual-Upgrade-1.5.0.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Testing upgrade to fixed  https://github.com/vmware/vic-product/issues/2342.

Add upgrade scripts from 1.5.0 to latest

---

docs/user_doc/vic_vsphere_admin/vch_compute.md

1587 sizewarnings

---

tests/manual-test-cases/Group7-Upgrade/7-07-Upgrade-1.5.1.md
tests/manual-test-cases/Group7-Upgrade/7-07-Upgrade-1.5.1.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-07-Manual-Upgrade-1.5.1.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-07-Manual-Upgrade-1.5.1.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Testing upgrade from 1.5.1 to latest.
[skip ci]

Add upgrade scripts from 1.5.1 to latest

---

.drone.yml

Use Harbor 1.7.4 temp build for integration testing.
Fixes #

Use Harbor 1.7.4 temp build

---

docs/user_doc/vic_vsphere_admin/vch_proxy.md

Fixes https://github.com/vmware/vic-product/issues/2319.
@renmaosheng can you please review or assign a reviewer? Thanks!

Added that proxy is used when logging in to registry

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md
docs/user_doc/vic_vsphere_admin/ts_orphaned_cvms.md

Added troubleshooting topics for Orphaned cVMS

---

docs/user_doc/vic_vsphere_admin/configure_vch.md
docs/user_doc/vic_vsphere_admin/image_store.md
docs/user_doc/vic_vsphere_admin/vch_general_settings.md
docs/user_doc/vic_vsphere_admin/vicmachine_options_ref.md

Fixes https://github.com/vmware/vic-product/issues/2368. 
@wjun and @yuyangbj can you please review? Thanks!

Documented --containers option

---

docs/user_doc/vic_vsphere_admin/client_network.md
docs/user_doc/vic_vsphere_admin/container_networks.md

Fixes https://github.com/vmware/vic-product/issues/2365.
@pureshine and @zhoumeina can you please review? Thanks!

Documented that client gateway is not mandatory in wizard

---

docs/user_doc/vic_app_dev/network_use_cases.md
docs/user_doc/vic_vsphere_admin/bridge_network.md
docs/user_doc/vic_vsphere_admin/inspect_vch.md
docs/user_doc/vic_vsphere_admin/vicmachine_options_ref.md

Fixes https://github.com/vmware/vic-product/issues/2367.
@yuyangbj and @wjun can you please review? Thanks!

Documented bridge network width option

---

.drone.yml
tests/auto_published_docs.sh

Test ci auto generate docs pipeline.
fixed https://github.com/vmware/vic-product/issues/877

[WIP]auto generate docs

---

docs/user_doc/book.json

Attempting to fix Google Analytics configuration

---

tests/manual-test-cases/Group7-Upgrade/7-05-Upgrade-1.4.4.robot
tests/resources/OVA-Util.robot

Upgrade from 1.4.4 to 1.5.0 then Upgrade to latest

---

tests/resources/OVA-Util.robot
tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Add Keywords for testing VCH Plugin functions

---

docs/user_doc/book.json

Attempting to implement Google Analytics on the 1.4 doc set.

Added analytics to 1.4 docs

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-18-Embeded-Linked-Mode.md
tests/manual-test-cases/Group5-Interoperability-Tests/5-18-Embeded-Linked-Mode.robot
tests/resources/nimbus-testbeds/vic-embededlinkmode.rb

1.Enhanced linked mode will out of support. Embeded Linked mode is the one
to replace Enhanced linked mode. Add such scenario for vic-product testing.
2. add new vic-embededlinkmode.rb to set up env
3. Extend timeout for Enhanced linked mode case
Fix  #2346

Add new case Embeded Linked mode

---

docs/user_doc/vic_vsphere_admin/troubleshoot_vic.md

Hi @stuclem , fixed the link in the Troubleshooting container topic.
Request you to approve.
Thanks!

Fixed link to Orphaned VMs topic

---

tests/manual-test-cases/Group7-Upgrade/7-02-Upgrade-1.3.0.robot
tests/manual-test-cases/Group7-Upgrade/7-03-Upgrade-1.3.1.robot
tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.0.robot
tests/manual-test-cases/Group7-Upgrade/7-05-Upgrade-1.4.4.robot
tests/manual-test-cases/Group7-Upgrade/7-06-Upgrade-1.5.0.robot
tests/manual-test-cases/Group7-Upgrade/7-07-Upgrade-1.5.1.robot
tests/resources/Docker-Util.robot
tests/resources/OVA-Util.robot
tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Test to ensure that VCH wizard can delete other versions,
fixed https://github.com/vmware/vic/issues/7131.

Using VCH wizard delete other versions

---

tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Add screenshot when getting vch count failure

---

tests/manual-test-cases/Group7-Upgrade/7-05-Upgrade-1.4.4.robot
tests/resources/OVA-Util.robot
tests/resources/VCH-Util.robot
tests/resources/page-objects/VC-Single-Sign-On-Util.robot
tests/resources/page-objects/Vsphere-VCH-Plugin-Util.robot

Fix fetch vch ip and count unstable issue

---

tests/manual-test-cases/Group2-OVA-Features/2-05-Customized-Configurations.robot

Wait till harbor containers are up then check syslogs.
Fixes #

Fix test for harbor syslog

---

tests/manual-test-cases/Group7-Upgrade/7-02-Upgrade-1.3.0.robot
tests/manual-test-cases/Group7-Upgrade/7-03-Upgrade-1.3.1.robot
tests/manual-test-cases/Group7-Upgrade/7-04-Upgrade-1.4.0.robot
tests/manual-test-cases/Group7-Upgrade/7-05-Upgrade-1.4.4.robot
tests/manual-test-cases/Group7-Upgrade/7-06-Upgrade-1.5.0.robot
tests/manual-test-cases/Group7-Upgrade/7-07-Upgrade-1.5.1.robot
tests/resources/OVA-Util.robot

Add a condition if vc version 6.0 then do not delete vch using UI

---

docs/user_doc/vic_vsphere_admin/interop.md

Fixes https://github.com/vmware/vic-product/issues/2249. 
@lazarin is this correct?

Added support statement for vRA 7.6

---

tests/resources/page-objects/VC-Single-Sign-On-Util.robot

Fix ci test login vc page failure

---

docs/user_doc/vic_users/container_provisioning_options_reference.md
docs/user_doc/vic_users/create_network.md

Hi @stuclem ,
Fixed comments from Lazarin and Jitin. Can you please approve this PR.
Fixes:  #928 
Thanks,
Vidya

Fixed VIC UI comments from Lazarin and Jitin.

---

tests/resources/VC-Util.robot

vc 6.7u2 command line of fetching psc output changed, so need to
modified scripts to support it.

Modified keyword of getting psc to support vc 6.7u2

---

.drone.yml

Update admiral version to latest.
Update harbor version to 1.7.5.

Update admiral and harbor integration version

---

installer/build/scripts/provisioners/provision_admiral.sh
installer/build/scripts/systemd/scripts/psc/get_token.sh
installer/fileserver/tasks/register.go

[WIP]Update admiral psc version to 1.5.3

---

installer/build/scripts/harbor/start_harbor.sh
installer/build/scripts/systemd/scripts/vic-appliance-environment.sh

Fix harbor gc does not work issue

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Update upgrade script for supporting from 1.5.2

---

docs/user_doc/SUMMARY.md
docs/user_doc/vic_vsphere_admin/SUMMARY.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance_ovftool.md

Hi @stuclem ,
I have documented the ovftool command and some of the options. 
Fixes #941 
Thanks!
Vidya

Documented ovftool options

---

docs/user_doc/vic_vsphere_admin/upgrade_vch.md

Hi @stuclem, I have added a line about the ports in the upgrade topic. Request your review.
Fixes #432 
Thanks,
Vidya

Added info about NAT based ports in the upgrade topic

---

tests/manual-test-cases/Group7-Upgrade/7-08-Upgrade-1.5.2.md
tests/manual-test-cases/Group7-Upgrade/7-08-Upgrade-1.5.2.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-08-Manual-Upgrade-1.5.2.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-08-Manual-Upgrade-1.5.2.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Add upgrade test case to from 1.5.2 to latest for fixed https://github.com/vmware/vic-product/issues/2457

Add upgrade test case to from 1.5.2 to latest

---

docs/user_doc/vic_cloud_admin/content_trust.md

Hi @stuclem 
I have added line per comment (https://github.com/vmware/vic-product/issues/1863#issuecomment-492118255) from reasonerjt about mixing signed and unsigned images in a project.
Fixes #1863 
Thanks,
Vidya

Updated the content for mixing signed and unsigned images

---

.drone.yml
tests/publish-ova-releases.sh

Add publish ova pipeline when triggering tag event

---

tests/resources/OVA-Util.robot

Randomly generated save diretory of vic machine files

---

docs/user_doc/vic_vsphere_admin/configure_vch.md

Hi @stuclem ,
I have added the line as per our email exchange. Request you to review it.
Fixes #2428 
Thanks,
Vidya

Clarified: –registry-ca replaces instead of adding certificates

---

docs/user_doc/vic_vsphere_admin/access_h5_ui.md

Hi @stuclem , can you please review this?
Fixes #2400 
Thanks,
Vidya

Added that appliance IP address is clickable

---

docs/user_doc/vic_vsphere_admin/configure_vch.md
docs/user_doc/vic_vsphere_admin/upgrade_vch.md
docs/user_doc/vic_vsphere_admin/upgrade_vch_options.md

Hi @stuclem , @wjun , and @jitinkumar2018 ,
I have updated the vic-machine configure command with the --rollback option and also added a note to run this command before rolling back a VCH upgrade.
Fixes #2399 
Thanks!
Vidya

Added --rollback option for vic-machine configure

---

docs/user_doc/vic_vsphere_admin/interop.md

Hi @stuclem ,
Request your review. 
Fixes #2416 
Thanks,
Vidya

Added support for NSX-T 2.4

---

docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md

Hi @stuclem 
I added info about the properties under Syslog configuration while deploying the appliance.
Fixes: #2427 
Thanks,
Vidya

Added configuration for forwarding appliance logs to syslog server

---

docs/user_doc/vic_vsphere_admin/vi_reqs.md

Hi @stuclem and @DanielXiao ,
Request you to review the updates.
Fixes #2248 
Thanks,
Vidya

Added support for 6.7 update 2

---

docs/user_doc/vic_vsphere_admin/configure_vch.md
docs/user_doc/vic_vsphere_admin/vch_cert_options.md

Hi @stuclem , @jitinkumar2018 , @DanielXiao 
Updated vic-machine create and configure with info for --tls-ca option. Request you to review the changes. 
Fixes #2472 
Thanks,
Vidya

Updated vic-machine create and configure with info for --tls-ca option

---

src/app/app.component.html

The last time I updated the latest update date, I hacked the output rather than updating the source. This PR fixes the source files for the landing page on https://vmware.github.io/vic-product/

Updated latest update date to reflect what's currently online

---

src/app/app.component.html

This is the source file for the landing page at https://vmware.github.io/vic-product/.

Updated source file for landing page

---

docs/user_doc/vic_vsphere_admin/access_h5_ui.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance_ovftool.md

Hi @stuclem ,
Made some minor edits and formatting changes. 
The ovf tool change is from the comment in https://github.com/vmware/vic-product/pull/2450
I had already merged the changes before getting this comment. 
Request you to please review.
Thanks,
Vidya

Misc edits and formatting changes

---

docs/user_doc/vic_vsphere_admin/client_network.md
docs/user_doc/vic_vsphere_admin/network_reqs.md

Fixes https://github.com/vmware/vic-product/issues/2492

Added that vic-machine must have access to client network

---

.gitignore

Ignoring doc generation files.

Updating node modules

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh
tests/manual-test-cases/Group7-Upgrade/7-09-Upgrade-1.5.3.md
tests/manual-test-cases/Group7-Upgrade/7-09-Upgrade-1.5.3.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-09-Manual-Upgrade-1.5.3.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-09-Manual-Upgrade-1.5.3.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Add upgrade scripts to support upgrade vic from v1.5.3

---

.drone.yml

update admiral version to v1.5.4

---

.gitignore
docs/user_doc/vic_vsphere_admin/download_vic.md

Fixes https://github.com/vmware/vic-product/issues/2456.
@vidya-v can you please approve? Thanks!

Added URL to UI builds

---

.gitignore
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance.md
docs/user_doc/vic_vsphere_admin/deploy_vic_appliance_ovftool.md

Fixes https://github.com/vmware/vic-product/issues/2504.
@reasonerjt is this correct? Thanks

Documented that Clair requires both HTTP and HTTPS proxies

---

.drone.yml

Update harbor version to 1.7.6

---

docs/user_doc/vic_vsphere_admin/container_networks.md

Fixes https://github.com/vmware/vic-product/issues/2468
@luwang-vmware are you the correct person to review this one? Thanks!

Documented how to expose ports on container network with published firewall policy

---

docs/user_doc/vic_vsphere_admin/interop.md

Fixes https://github.com/vmware/vic-product/issues/2163.
@luwang-vmware can you please review?

Documented that VCHA is supported.

---

docs/user_doc/vic_overview/intro_to_containers.md

test commit

---

docs/user_doc/vic_vsphere_admin/vi_reqs.md

Removed 6.0 from supported vSphere versions

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Update upgrade.sh to support upgrade from v1.5.4

---

tests/manual-test-cases/Group7-Upgrade/7-10-Upgrade-1.5.4.md
tests/manual-test-cases/Group7-Upgrade/7-10-Upgrade-1.5.4.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-10-Manual-Upgrade-1.5.4.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-10-Manual-Upgrade-1.5.4.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Add upgrade test cases for version 1.5.4

---

.drone.yml

Removed admiral field for picking latest admiral version

---

.drone.yml

Update admiral version to 1.5.5

---

docs/user_doc/vic_vsphere_admin/vch_compute.md

Added command to deploy vCenter Server to a cluster in a folder.

Updated vic-machine cmd for cluster under folder

---

installer/build/ova-manifest.json
installer/build/scripts/harbor/cleanup_redis_cache.sh
installer/build/scripts/harbor/harbor.service

Fixed bug for cannot add an image to harbor when previously deleted

---

docs/user_doc/vic_users/container_provisioning_options_reference.md

Fixed storage read-only option

---

.drone.yml

Update harbor version to 1.7.7

---

.drone.yml

Update admiral version to latest

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

testing, fixed https://github.com/vmware/vic-product/issues/2579

Support upgrade vic product from v1.5.5 using upgrade scripts

---

tests/manual-test-cases/Group7-Upgrade/7-11-Upgrade-1.5.5.md
tests/manual-test-cases/Group7-Upgrade/7-11-Upgrade-1.5.5.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-11-Manual-Upgrade-1.5.5.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-11-Manual-Upgrade-1.5.5.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Add upgrade vic appliance test cases from 1.5.5

---

installer/fileserver/html/package.json
installer/fileserver/test/package-lock.json
installer/fileserver/test/package.json

Signed-off-by: Yogi_Wang <yawang@vmware.com

[vulnerability] Upgrade vulnerability package in vic product

---

.drone.yml

Update admiral version to 1.5.6

---

.drone.yml
installer/build/build.sh
tests/resources/Docker-Util.robot
tests/resources/OVA-Util.robot
tests/test-cases/Group3-Admiral/3-01-Admiral-UI.robot
tests/test-cases/Group4-Harbor/4-01-Harbor.robot

Fixed that docker pull images failed due to dockerhub limit

---

installer/build/scripts/upgrade/upgrade.sh
installer/build/scripts/upgrade/util.sh

Supported upgrade from 1.5.6 to latest

---

.drone.yml

Update harbor version

---

.drone.yml
tests/check-org-membership.sh
tests/pass-rate.sh

Fixed to access github api error using token

---

tests/manual-test-cases/Group7-Upgrade/7-12-Upgrade-1.5.7.md
tests/manual-test-cases/Group7-Upgrade/7-12-Upgrade-1.5.7.robot
tests/manual-test-cases/Group7-Upgrade/TestCases.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-12-Manual-Upgrade-1.5.7.md
tests/manual-test-cases/Group8-Manual-Upgrade/8-12-Manual-Upgrade-1.5.7.robot
tests/manual-test-cases/Group8-Manual-Upgrade/TestCases.md

Add upgrade test case from 1.5.7

---

tests/check-org-membership.sh

Hidden github token for the ci output

---

tests/manual-test-cases/Group5-Interoperability-Tests/5-01-Distributed-Switch-No-Cluster.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-03-Multiple-Datacenter.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-04-Multiple-Cluster.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-05-Enhanced-Linked-Mode.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-06-1-VSAN-Simple.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-09-Network-Folder.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-15-NFS-Datastore.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-16-vMotion-VCH-Appliance.robot
tests/manual-test-cases/Group5-Interoperability-Tests/5-17-FC-Datastore.disabled
tests/manual-test-cases/Group5-Interoperability-Tests/5-18-Embeded-Linked-Mode.robot
tests/resources/Nimbus-Util.robot

Fixed that the nimbus commands did not work
